Update Xinmeitulu & Meitu.top: Support filter & search with filter
keiyoushi/extensions-source pull request #1025
Opened 2024-02-05 16:44 UTC by cuong-tran

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [X] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-05 17:04 UTC, stevenyomi requested changes

2024-02-05 17:04 UTC, stevenyomi commented on src/all/meituatop/src/eu/kanade/tachiyomi/extension/all/meituatop/MeituaTop.kt
> +        return if (Locale.getDefault().equals("zh")) {
You should translate the `SManga.genre` field too.

2024-02-06 05:51 UTC, AwkwardPeak7 submitted a review, later dismissed

2024-02-06 05:53 UTC, stevenyomi requested changes

2024-02-06 05:53 UTC, stevenyomi commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +            RegionFilter(getRegionList()),
Translate this too.

2024-02-06 07:35 UTC, cuong-tran commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +            RegionFilter(getRegionList()),
It's already translated:
`    private fun getRegionList(): Array<Pair<String?, String>> {
        return if (Locale.getDefault().equals("zh")) {
            arrayOf(
                null to "全部",
                "zhongguodalumeinyu" to "中国大陆美女",
                "taiguomeinyu" to "泰国美女",
                "ribenmeinyu" to "日本美女",
                "hanguomeinyu" to "韩国美女",
                "taiwanmeinyu" to "台湾美女",
                "oumeimeinyu" to "欧美美女",
            )
        } else {
            arrayOf(
                null to "All",
                "zhongguodalumeinyu" to "Chinese beauty",
                "taiguomeinyu" to "Thailand beauty",
                "ribenmeinyu" to "Japanese beauty",
                "hanguomeinyu" to "Korean beauty",
                "taiwanmeinyu" to "Taiwanese beauty",
                "oumeimeinyu" to "European & American beauty",
            )
        }
    }`

2024-02-06 07:55 UTC, stevenyomi commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +            RegionFilter(getRegionList()),
```kotlin
    override fun popularMangaFromElement(element: Element) = SManga.create().apply {
        setUrlWithoutDomain(element.select("figure > a").attr("abs:href"))
        title = element.select("figcaption").text()
        thumbnail_url = element.select("img").attr("abs:data-original-")
        genre = element.select("a.tag").joinToString(", ") { it.text() }  // <--- THIS
    }
```

2024-02-06 17:21 UTC, cuong-tran commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +            RegionFilter(getRegionList()),
Function 'popularMangaFromElement' only query list of popular mangas, which won't use 'genre'.

Also the 'tag' which the site's using are completely various, much like hashtag than genre. They are not a fixed list so it's unable to translate them.

2024-02-06 17:26 UTC, stevenyomi commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +            RegionFilter(getRegionList()),
Do `removeSuffix("写真")` and the last tag of each entry can be translated.

2024-02-06 20:01 UTC, cuong-tran commented
Added genre translation, but again, genre won't show in manga browse list & it's not available in manga's detail page. Is there anyway to pass `SManga` from `popularMangaFromElement` to `mangaDetailsParse`?

2024-02-06 20:02 UTC, stevenyomi commented
> Added genre translation, but again, genre won't show in manga browse list & it's not available in manga's detail page. Is there anyway to pass `SManga` from `popularMangaFromElement` to `mangaDetailsParse`?

Oh right. Probably open an issue in Mihon lol.

2024-02-06 20:06 UTC, stevenyomi submitted a review, later dismissed

2024-02-06 20:51 UTC, cuong-tran commented
Don't merge this yet. I'm doing more translation.

2024-02-06 21:09 UTC, stevenyomi requested changes

2024-02-06 21:09 UTC, stevenyomi commented on src/all/meituatop/src/eu/kanade/tachiyomi/extension/all/meituatop/MeituaTop.kt
> +        if (Locale.getDefault().equals("zh")) return chinese
```suggestion
        if (Locale.getDefault().getLanguage() == "zh") return chinese
```

2024-02-06 21:09 UTC, stevenyomi commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +        title = document.select(".container > h1").text().trim()
```suggestion
        title = document.select(".container > h1").text()
```
Jsoup already trims the text.

2024-02-06 21:09 UTC, stevenyomi commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +        if (Locale.getDefault().equals("zh")) return it
Same here.

2024-02-06 21:09 UTC, stevenyomi commented on src/all/xinmeitulu/src/eu/kanade/tachiyomi/extension/all/xinmeitulu/Xinmeitulu.kt
> +            "相关编号" -> "Related"
Should be something like issue number.

2024-02-07 03:58 UTC, closed without merging

2024-02-07 03:58 UTC, beerpiss commented
Closing because you seem to not have a good enough command of the Chinese language and are resorting to machine translation. Feel free to maintain the English versions on your own.