Rework the mangareader multisrc
keiyoushi/extensions-source pull request #1201
Opened 2024-02-11 16:14 UTC by Secozzi

A lot of websites using the mangareader theme has popped up since the multisrc theme was made, so this rework aims to make it easier to add them.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-12 11:15 UTC, AwkwardPeak7 requested changes

2024-02-12 11:15 UTC, AwkwardPeak7 commented on multisrc/overrides/mangareader/comickiba/src/Manhuagold.kt
> +    "views",
explicitly specify `views` paramter for better readibiltiy

2024-02-12 11:15 UTC, AwkwardPeak7 commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangareader/MangaReader.kt
> +        throw NotImplementedError()
if sources are expected to implement these methods, then make them abstract

2024-02-12 12:40 UTC, AwkwardPeak7 commented on multisrc/overrides/mangareader/mangafire/src/MangaFire.kt
> +    "recently_updated",
here too

2024-02-12 12:40 UTC, stevenyomi requested changes
Move `open val`s to the constructor like #931.

2024-02-12 12:52 UTC, stevenyomi requested changes

2024-02-12 12:52 UTC, stevenyomi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangareader/MangaReader.kt
> +import eu.kanade.tachiyomi.source.online.ParsedHttpSource
This source is not a conventional parsed HTTP source. Do not inherit `ParsedHttpSource` just to reuse the "field/functions names". Declare your own ones instead.

2024-02-12 12:52 UTC, stevenyomi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangareader/MangaReader.kt
> +        "canceled" -> SManga.CANCELLED
Use comma to join conditions with same result.

2024-02-12 12:52 UTC, stevenyomi commented on multisrc/overrides/mangareader/mangafire/src/MangaFire.kt
>          }
```suggestion
        thumbnail_url = element.selectFirst("img")!!.imgAttr()
```

2024-02-13 12:56 UTC, stevenyomi commented
Let's merge this after the migration. It's too painful to edit in the current project architecture.

2024-02-13 23:50 UTC, stevenyomi commented
Continued in #1241

2024-02-13 23:50 UTC, closed without merging