Add RawMangas
keiyoushi/extensions-source pull request #1276
Opened 2024-02-15 16:18 UTC by TeflonOfJoy

Closes #1267

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-15 18:00 UTC, beerpiss requested changes

2024-02-15 18:00 UTC, beerpiss commented on src/ja/rawmangas/build.gradle
> +apply from: "$rootDir/common.gradle"
```suggestion
apply from: "$rootDir/common.gradle"

```
Add an ending newline.

2024-02-16 12:23 UTC, AwkwardPeak7 commented on src/ja/rawmangas/build.gradle
> +
```suggestion
```

2024-02-16 12:24 UTC, AwkwardPeak7 approved these changes

2024-02-16 12:27 UTC, merged