Add SpeedBinb multisrc
keiyoushi/extensions-source pull request #1277
Opened 2024-02-15 16:27 UTC by beerpiss

SpeedBinb is a manga reader for various official Japanese manga sites. As it is only a reader, parsing of manga/chapter lists is left to the inherited class to implement.

Unsure if this should be a multisrc, suggestions on more appropriate places are welcome.

Closes #1173 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-15 18:12 UTC, FourTOne5 requested changes

2024-02-15 18:12 UTC, FourTOne5 commented on lib-multisrc/speedbinb/src/eu/kanade/tachiyomi/multisrc/speedbinb/SpeedBinb.kt
> +abstract class SpeedBinb(
```suggestion
abstract class SpeedBinbReader(
```
Make the name specific?

2024-02-15 18:34 UTC, beerpiss commented on lib-multisrc/speedbinb/src/eu/kanade/tachiyomi/multisrc/speedbinb/SpeedBinb.kt
> +abstract class SpeedBinb(
Sure. b039b563

2024-02-16 00:03 UTC, AwkwardPeak7 commented
Maybe make it a regular lib and provide `parseSpeedBinbReader` method or similar.

2024-02-16 03:57 UTC, beerpiss commented
> Maybe make it a regular lib and provide `parseSpeedBinbReader` method or similar.

2024-02-16 04:01 UTC, beerpiss commented
> Maybe make it a regular lib and provide `parseSpeedBinbReader` method or similar.

Would need to pass in a few things from the source (client, headers, a Json instance) but it works either way.

Would also require remembering to add in the interceptor for descrambling.

2024-02-16 10:35 UTC, FourTOne5 commented
Could probably make the reader throw if the interceptor isn't in the chain

2024-02-16 12:05 UTC, AwkwardPeak7 requested changes

2024-02-16 12:05 UTC, AwkwardPeak7 commented on lib/speedbinb/src/main/java/eu/kanade/tachiyomi/lib/speedbinb/TextInterceptor.kt
is it possible to make the library version of `TextInterceptor` generic enough for this instead of copy pasting the whole thing?
Could possibly make it so it simply draws the given text and use that version in the extensions using the current version.

can do it in a spearate pr

2024-02-16 12:05 UTC, AwkwardPeak7 commented on src/ja/comicmeteor/src/eu/kanade/tachiyomi/extension/ja/comicmeteor/ComicMeteor.kt
> +        "https://comic-meteor.jp/wp-admin/admin-ajax.php?action=get_flex_titles_for_toppage&page=$page&get_num=16",
```suggestion
        "$baseUrl/wp-admin/admin-ajax.php?action=get_flex_titles_for_toppage&page=$page&get_num=16",
```

2024-02-16 13:41 UTC, beerpiss commented on lib/speedbinb/src/main/java/eu/kanade/tachiyomi/lib/speedbinb/TextInterceptor.kt
Made `TextInterceptor` not render the heading if `creator` is empty.

2024-02-17 05:30 UTC, AwkwardPeak7 requested changes

2024-02-17 05:30 UTC, AwkwardPeak7 commented on lib-multisrc/comicgamma/build.gradle.kts
> +    implementation(project(":lib:speedbinb"))
```suggestion
    api(project(":lib:speedbinb"))
```

2024-02-17 06:06 UTC, closed without merging