Add todaymanga
keiyoushi/extensions-source pull request #1289
Opened 2024-02-16 11:49 UTC by Secozzi

Closes #1183

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-16 12:21 UTC, AwkwardPeak7 requested changes

2024-02-16 12:21 UTC, AwkwardPeak7 commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        val genreFilter = filterList.find { it is GenreFilter } as GenreFilter
```suggestion
        val categoryFilter = filterList.filterIsInstance<CategoryFilter>().first()
        val genreFilter = filterList.filterIsInstance<GenreFilter>().first()
```

2024-02-16 14:29 UTC, stevenyomi requested changes

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        return GET(url.build(), headers)
```suggestion
        }.build()

        return GET(url, headers)
```

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        document.selectFirst(".serie")!!.run {
```suggestion
        with(document.selectFirst(".serie")!!) {
```

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        thumbnail_url = element.selectFirst("img")?.imgAttr()
```suggestion
        thumbnail_url = element.selectFirst("img")!!.imgAttr()
```

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        thumbnail_url = element.selectFirst("img")?.imgAttr()
```suggestion
        thumbnail_url = element.selectFirst("img")!!.imgAttr()
```

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +            thumbnail_url = selectFirst("img")?.imgAttr()
```suggestion
            thumbnail_url = selectFirst("img")!!.imgAttr()
```

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +            document.selectFirst(".serie-summary")?.also { summary ->
Is this expected to be nullable? If not, use `val summary = ...!!`.

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        element.selectFirst("a")!!.run {
```suggestion
        with(element.selectFirst("a")!!) {
```

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +            .getOrNull() ?: 0L
```suggestion
        return try {
            DATE_FORMATTER.parse(dateStr)!!.time
        } catch (_: Throwable) {
            0L
        }
```

2024-02-16 14:29 UTC, stevenyomi commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +    }
```suggestion
    private val DATE_FORMATTER by lazy {
        SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)
    }
```

2024-02-17 04:08 UTC, beerpiss requested changes

2024-02-17 04:08 UTC, beerpiss commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        } catch (_: Throwable) {
```suggestion
        } catch (_: ParseException) {
```

[DateFormat#parse(String)](https://docs.oracle.com/javase/8/docs/api/java/text/DateFormat.html#parse-java.lang.String-) doesn't return null, so you only need to catch [ParseException](https://docs.oracle.com/javase/8/docs/api/java/text/ParseException.html). Catching too wide may suppress other issues.

2024-02-17 04:08 UTC, beerpiss commented on src/en/todaymanga/src/eu/kanade/tachiyomi/extension/en/todaymanga/TodayManga.kt
> +        return parsedDate
```suggestion
        val relativeDate = this.split(" ").firstOrNull()
            ?.replace("one", "1")
            ?.replace("a", "1")
            ?.toIntOrNull()
            ?: return 0L

        when {
            // parse: 30 seconds ago
            "second" in this -> now.add(Calendar.SECOND, -relativeDate)

            // parses: "42 minutes ago"
            "minute" in this -> now.add(Calendar.MINUTE, -relativeDate)

            // parses: "1 hour ago" and "2 hours ago"
            "hour" in this -> now.add(Calendar.HOUR, -relativeDate)

            // parses: "2 days ago"
            "day" in this -> now.add(Calendar.DAY_OF_YEAR, -relativeDate)

            // parses: "2 weeks ago"
            "week" in this -> now.add(Calendar.WEEK_OF_YEAR, -relativeDate)

            // parses: "2 months ago"
            "month" in this -> now.add(Calendar.MONTH, -relativeDate)

            // parse: "2 years ago"
            "year" in this -> now.add(Calendar.YEAR, -relativeDate)
        }
        return now.timeInMillis
```

2024-02-17 14:42 UTC, AwkwardPeak7 approved these changes

2024-02-17 14:42 UTC, merged