Add source MajorScans "tr"
keiyoushi/extensions-source pull request #1460
Opened 2024-02-21 19:16 UTC by mohamedotaku

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-23 09:26 UTC, AwkwardPeak7 requested changes

2024-02-23 09:26 UTC, AwkwardPeak7 commented on src/tr/majorscans/build.gradle
> +    baseUrl = 'https://www.majorscans.com/'
```suggestion
    baseUrl = 'https://www.majorscans.com'
```

2024-02-23 18:41 UTC, mohamedotaku commented on src/tr/majorscans/build.gradle
> +    baseUrl = 'https://www.majorscans.com/'
### **_Ok_**

2024-02-26 12:34 UTC, AwkwardPeak7 approved these changes

2024-02-26 12:34 UTC, merged