add readmanga
keiyoushi/extensions-source pull request #1505
Opened 2024-02-23 14:22 UTC by Secozzi

Closes #1472

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-23 14:41 UTC, beerpiss requested changes

2024-02-23 14:41 UTC, beerpiss commented on src/ja/readmangaat/src/eu/kanade/tachiyomi/extension/ja/readmangaat/ReadMangaAt.kt
> +        Filter.Header("Ignored when using text search"),
The code in `searchMangaRequest` prioritizes the genre filter over text search though?

2024-02-27 14:43 UTC, AwkwardPeak7 requested changes

2024-02-27 14:43 UTC, AwkwardPeak7 commented on src/ja/readmangaat/src/eu/kanade/tachiyomi/extension/ja/readmangaat/ReadMangaAt.kt
> +                addQueryParameter("s", query)
prefer query search over genre

2024-02-28 15:36 UTC, AwkwardPeak7 approved these changes

2024-02-28 15:36 UTC, merged