Add Alone Scanlator
keiyoushi/extensions-source pull request #1514
Opened 2024-02-23 20:24 UTC by ttony2chopper

Closes #157
 
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-23 21:53 UTC, vetleledaal commented on src/pt/alonescanlator/build.gradle
> +    overrideVersionCode = 1
```suggestion
    overrideVersionCode = 0
```

2024-02-26 12:48 UTC, AwkwardPeak7 requested changes

2024-02-26 12:48 UTC, AwkwardPeak7 commented on src/pt/alonescanlator/src/eu/kanade/tachiyomi/extension/pt/alonescanlator/AloneScanlator.kt
the site seems to be using `newChapterEndpoing`

2024-02-27 02:24 UTC, ttony2chopper commented on src/pt/alonescanlator/src/eu/kanade/tachiyomi/extension/pt/alonescanlator/AloneScanlator.kt
Resolve: https://github.com/keiyoushi/extensions-source/pull/1514/commits/fd85a709940d23fae4d0fe7e5e91111ddfc479e6

2024-02-27 14:16 UTC, AwkwardPeak7 approved these changes

2024-02-27 14:16 UTC, merged