Fix BlackoutComics selectors
keiyoushi/extensions-source pull request #1547
Opened 2024-02-25 23:38 UTC by ttony2chopper

Closes #1402 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-02-25 23:41 UTC, ttony2chopper commented
The source added additional HTML tags to "block" data extraction.  And possibly other similar bugs will be opened up because of other changes.

2024-02-26 13:02 UTC, AwkwardPeak7 approved these changes

2024-02-26 13:04 UTC, AwkwardPeak7 requested changes

2024-02-26 13:04 UTC, AwkwardPeak7 commented on src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt
> +        title = element.selectFirst("p:not(.hidden), span.text-comic")?.text() ?: "Manga"
```suggestion
        title = element.selectFirst("p:not(.hidden), span.text-comic")!!.text()
```

2024-02-26 13:04 UTC, AwkwardPeak7 commented on src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt
> +        title = row.selectFirst("div.trailer-content > h2:not(.hidden)")?.text() ?: "Manga"
```suggestion
        title = row.selectFirst("div.trailer-content > h2:not(.hidden)")!!.text)
```

2024-02-26 14:15 UTC, AwkwardPeak7 approved these changes

2024-02-26 14:15 UTC, merged