change domain for nettruyen
keiyoushi/extensions-source pull request #1716
Opened 2024-03-05 16:07 UTC by Taki132

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x]  explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension
Issuse about changing source
#1711

2024-03-06 12:56 UTC, AwkwardPeak7 commented
`https://www.nettruyenbb.com` still works?

2024-03-06 13:35 UTC, trungsamset0 commented
> `https://www.nettruyenbb.com` still works?

nope

2024-03-06 13:49 UTC, AwkwardPeak7 commented
![image](https://github.com/keiyoushi/extensions-source/assets/48650614/84135007-df3d-474f-809f-3fabb8bd64ae)
¯\\\_(ツ)\_/¯

2024-03-06 13:59 UTC, trungsamset0 commented
> ![image](https://private-user-images.githubusercontent.com/48650614/310521441-84135007-df3d-474f-809f-3fabb8bd64ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzM4MTksIm5iZiI6MTcwOTczMzUxOSwicGF0aCI6Ii80ODY1MDYxNC8zMTA1MjE0NDEtODQxMzUwMDctZGYzZC00NzRmLTgwOWYtM2ZhYmI4YmQ2NGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzNTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwOWRiYzZjNjZkNmYyYzI3N2MyNThhOTE4N2I4NjFkYTY4ZTY1YmM4NGVmOTk4ZTBhZmE2N2M5YzgzZGE5YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6DZJ6-qwtkDo8Jga7MCeL4BsTxoYeuzf20BcqWPdAag) ¯\_(ツ)_/¯

wait a minute, it just work again

2024-03-06 16:02 UTC, Taki132 commented
> ![image](https://github.com/keiyoushi/extensions-source/assets/48650614/84135007-df3d-474f-809f-3fabb8bd64ae)
> ¯\\\_(ツ)\_/¯

So it'ss not work on tachiyomi 🤡
![Screenshot_20240306_230215_TachiyomiJ2K.png](https://github.com/keiyoushi/extensions-source/assets/92381976/1f989a9c-a8dd-4c19-b7cc-a4262f9a63ff)

2024-03-06 16:04 UTC, Taki132 commented
It's down again 😭

2024-03-06 16:32 UTC, trungsamset0 commented
![Screenshot_2024-03-06-23-31-43-07_be80aec1db9a2b53c9d399db0c602181.jpg](https://github.com/keiyoushi/extensions-source/assets/39975426/0622977e-68a8-4efb-80ac-b6a44ab5cc49)

The newest source is https://www.nettruyenee.com/

2024-03-06 16:56 UTC, Taki132 commented
> ![Screenshot_2024-03-06-23-31-43-07_be80aec1db9a2b53c9d399db0c602181.jpg](https://github.com/keiyoushi/extensions-source/assets/39975426/0622977e-68a8-4efb-80ac-b6a44ab5cc49)
> 
> The newest source is https://www.nettruyenee.com/

Oke để em reverse lại domain

2024-03-06 17:36 UTC, Taki132 commented
Xong rồi nhé anh check lại rồi merge giúp em với (sr anh vì hành tá cái commit dở hơi tí) em đang là học sinh nên ko biết qua nhiều về code nên nếu sai xót về thư viện hay gì mong anh giúp đỡ

2024-03-06 17:37 UTC, Taki132 commented
@AwkwardPeak7 it's done bro

2024-03-06 19:56 UTC, beerpiss requested changes
To link an issue to a PR, either change it in the sidebar, or edit the description to say `Closes #<issue>`.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2024-03-06 23:45 UTC, Taki132 commented
> To link an issue to a PR, either change it in the sidebar, or edit the description to say `Closes #<issue>`.
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
> 

Okay I changed the comment

2024-03-07 11:00 UTC, cuong-tran commented
NetTruyen keeps getting blocked and changes domain all the time. Why not implement a preferences to allow user to change domain themselves while waiting for extension update?

2024-03-08 03:29 UTC, cuong-tran commented
Since both NetTruyen & NhatTruyen using WPComics and often change their domain, maybe we should implement Customizable in WPComics instead of NetTruyen specifically.

2024-03-08 09:56 UTC, AwkwardPeak7 commented on src/vi/nettruyen/src/eu/kanade/tachiyomi/extension/vi/nettruyen/NetTruyen.kt
> +class NetTruyen : WPComics("NetTruyen", "https://www.nettruyenee.com", "vi", SimpleDateFormat("dd/MM/yy", Locale.getDefault()), null) {
```suggestion

class NetTruyen : WPComics("NetTruyen", "https://www.nettruyenee.com", "vi", SimpleDateFormat("dd/MM/yy", Locale.getDefault()), null) {
```

2024-03-08 10:01 UTC, AwkwardPeak7 approved these changes

2024-03-08 10:01 UTC, merged