New source: Arabs Hentai (ar)
keiyoushi/extensions-source pull request #1842
Opened 2024-03-12 18:24 UTC by cuong-tran

Close: #19

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-03-12 18:32 UTC, vetleledaal commented on src/ar/arabshentai/src/eu/kanade/tachiyomi/extension/ar/arabshentai/ArabsHentai.kt
> +        val url = "$baseUrl/page/$page/?s=$query".toHttpUrl().newBuilder()
You need to escape the query properly

2024-03-13 10:11 UTC, AwkwardPeak7 requested changes
rebase on main

2024-03-13 10:11 UTC, AwkwardPeak7 commented on src/ar/arabshentai/src/eu/kanade/tachiyomi/extension/ar/arabshentai/ArabsHentai.kt
> +                }
```suggestion
            document.selectFirst(".content")!!.run {
                thumbnail_url = selectFirst(".sheader .poster img")?.imgAttr()
                title = selectFirst(".sheader .data h1")!!.text()
```

2024-03-13 10:11 UTC, AwkwardPeak7 commented on src/ar/arabshentai/src/eu/kanade/tachiyomi/extension/ar/arabshentai/ArabsHentai.kt
> +        "div b:contains(نوع العمل) + span a"
inline these

2024-03-13 10:11 UTC, AwkwardPeak7 commented on src/ar/arabshentai/src/eu/kanade/tachiyomi/extension/ar/arabshentai/ArabsHentai.kt
> +        }
```suggestion
        return try {
            dateFormat.parse(this)!!.time
        } catch (_: ParseException) {
            0L
        }
```

2024-03-13 10:11 UTC, AwkwardPeak7 commented on src/ar/arabshentai/src/eu/kanade/tachiyomi/extension/ar/arabshentai/ArabsHentai.kt
> +                    }
```suggestion
                genreList = client.newCall(genresRequest()).execute()
                    .asJsoup()
                    .let(::parseGenres)
```

2024-03-14 17:48 UTC, merged