HentaiSlayer: translate "alternative name"
keiyoushi/extensions-source pull request #1843
Opened 2024-03-12 18:49 UTC by cuong-tran

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-03-13 10:16 UTC, AwkwardPeak7 requested changes
rebase on main

2024-03-13 10:16 UTC, AwkwardPeak7 commented on src/ar/hentaislayer/src/eu/kanade/tachiyomi/extension/ar/hentaislayer/HentaiSlayer.kt
> +                    genre = select("span p.drop-shadow-sm").text()
```suggestion
            element.selectFirst("div#card-real a")!!.run {
                setUrlWithoutDomain(absUrl("href"))
                selectFirst("figure")!!.run {
                    selectFirst("img.object-cover")!!.run {
                        thumbnail_url = imgAttr()
                        title = attr("alt")
                    }
                    genre = select("span p.drop-shadow-sm").text()
```
title and url is mandatory and should be populated

2024-03-13 10:16 UTC, AwkwardPeak7 commented on src/ar/hentaislayer/src/eu/kanade/tachiyomi/extension/ar/hentaislayer/HentaiSlayer.kt
> +    override fun popularMangaRequest(page: Int) =
it is fine to leave them on same line

2024-03-13 10:16 UTC, AwkwardPeak7 commented on src/ar/hentaislayer/src/eu/kanade/tachiyomi/extension/ar/hentaislayer/HentaiSlayer.kt
> +                }
```suggestion
            document.selectFirst("main section")!!.run {
                selectFirst("img#manga-cover")!!.run {
                    thumbnail_url = imgAttr()
                    title = attr("alt")
                }
```

2024-03-13 10:16 UTC, AwkwardPeak7 commented on src/ar/hentaislayer/src/eu/kanade/tachiyomi/extension/ar/hentaislayer/HentaiSlayer.kt
> +                        title = it
should set title in one place. could do `title = <attempt one> ?: <attempt two>!!`

2024-03-13 15:22 UTC, stevenyomi commented on src/ar/hentaislayer/src/eu/kanade/tachiyomi/extension/ar/hentaislayer/HentaiSlayer.kt
> +                    genre = select("span p.drop-shadow-sm").text()
And replace `run()` with `with()`.

2024-03-14 17:24 UTC, stevenyomi requested changes
Revert all the format changes in your PR.

2024-03-15 17:28 UTC, merged