WPComics update & add new sources
keiyoushi/extensions-source pull request #1909
Opened 2024-03-15 20:26 UTC by cuong-tran

- WPComics:
  - Query for genres instead of hard-code them
  - Info: add Alternative name
  - Use i18n to support multi-language
  - Open some methods for future sources to override if needed
- XoxoComics/NetTruyen/NhatTruyen:
  - Follow WPComics update
  - Fix JManga's NextPageSelector
  - Fix JManga's wrong file location
- New sources: nettruyenx.com, nhattruyens.com, nettruyenco.vn (they all have different number of mangas)

Close #1423 

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [X] Have removed `web_hi_res_512.png` when adding a new extension

2024-03-18 04:29 UTC, AwkwardPeak7 requested changes

2024-03-18 04:29 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/src/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
> +        val completedWords = listOf("Complete", intl["STATUS_COMPLETED"])
don't use `intl` here

2024-03-18 04:29 UTC, AwkwardPeak7 commented on src/vi/nhattruyens/src/eu/kanade/tachiyomi/extension/vi/nhattruyens/NhatTruyenS.kt
> +    null,
nitpick: specify parameter name so it is more readable
here and other as well

2024-03-18 04:29 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/src/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
> +    open val intl by lazy {
don't use lazy

2024-03-18 04:29 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/src/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
> +        return GET(url.toString().replaceSearchPath(), headers)
not too familiar with `WpComics` but is it possible to refactor out the `replaceSearchPath`?

2024-03-18 04:52 UTC, AwkwardPeak7 requested changes

2024-03-18 04:52 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/assets/i18n/messages_ja.properties
is this mtl? if so consider removing it

2024-03-18 04:52 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/src/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
>          .add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0")
do the sources work same with mobile useragents? if so probably better to remove hardcoded useragent.

2024-03-18 04:52 UTC, cuong-tran commented on lib-multisrc/wpcomics/src/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
> +        return GET(url.toString().replaceSearchPath(), headers)
I don't really understand what do you mean by refactor out. Could you elaborate more?

2024-03-18 04:55 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/src/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
> +        return GET(url.toString().replaceSearchPath(), headers)
I mean remove it, if possible.

2024-03-18 11:31 UTC, cuong-tran commented on lib-multisrc/wpcomics/assets/i18n/messages_ja.properties
only the "GENRES_RESET" which was currently using English. The rest are moved from original JManga.

2024-03-19 08:36 UTC, AwkwardPeak7 requested changes

2024-03-19 08:36 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/src/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
>          .add("Referer", baseUrl)
use `super.headersBuilder()` to keep default useragent

also referer should be "$baseUrl/" since regular browsers send the trailing slash

2024-03-19 08:36 UTC, AwkwardPeak7 commented on src/en/xoxocomics/src/eu/kanade/tachiyomi/extension/en/xoxocomics/XoxoComics.kt
> +    lang = "en",
I didn't meant named argument for these too since they are part of the convention. I should have been more clear

2024-03-19 08:36 UTC, AwkwardPeak7 commented on lib-multisrc/wpcomics/assets/i18n/messages_ja.properties
then it should be fine

2024-03-19 16:05 UTC, AwkwardPeak7 approved these changes

2024-03-19 16:06 UTC, merged