Update Url Mangalek "ar"
keiyoushi/extensions-source pull request #1992
Opened 2024-03-20 04:09 UTC by mohamedotaku

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-03-21 17:31 UTC, AwkwardPeak7 commented
thoughts on [this](https://github.com/keiyoushi/extensions-source/issues/1999#issuecomment-2009348556)?

2024-03-21 17:50 UTC, mohamedotaku commented
> thoughts on [this](https://github.com/keiyoushi/extensions-source/issues/1999#issuecomment-2009348556)?

If you check these sites, you will find that they face the same problem at the same time. If one of them goes out of service, they all go out of service, and if one of them changes his Url, they all change it. They are all copies of each other.

I still don't know what's right for them. Should they be collected in one extension and have a list of Urls so that the user can choose the sites he wants. Or just leave them divided into different extensions and add the option to change the Urls for the user.

2024-03-21 17:56 UTC, AwkwardPeak7 commented
if you can provide all the different mirrors of mangalek, then it should be put in a single extension as mirrors.

2024-03-21 18:01 UTC, mohamedotaku commented
> if you can provide all the different mirrors of mangalek, then it should be put in a single extension as mirrors.

It's easy for Mangalek. The problem is with other sites like Manga Stars and Manga Spark ... They are look like Mangalik and they have same problem of mangalik.

2024-03-21 18:18 UTC, mohamedotaku commented
https://like-manga.net/
https://lekmanga.com/
https://lekmanga.net/
https://manga-lek.org/

2024-03-21 18:52 UTC, LoverFreedom commented
> > if you can provide all the different mirrors of mangalek, then it should be put in a single extension as mirrors.
> 
> It's easy for Mangalek. The problem is with other sites like Manga Stars and Manga Spark ... They are look like Mangalik and they have same problem of mangalik.

And Mangalionz and Mangalink

2024-03-22 16:08 UTC, AwkwardPeak7 requested changes
put the url in a constant val at top of file and use that here and in `defaultBaseUrl`;
did you run this to make sure it works?

2024-03-23 09:46 UTC, AwkwardPeak7 approved these changes

2024-03-23 09:46 UTC, merged