ReadComicFree Source
keiyoushi/extensions-source pull request #2209
Opened 2024-04-01 04:17 UTC by barrelltitor

Closes #1571

Search path segment is a bit ugly, if anyone knows a better way to do it I'd be happy to change

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-04-01 11:36 UTC, AwkwardPeak7 requested changes

2024-04-01 11:36 UTC, AwkwardPeak7 commented on src/en/readcomicfree/src/eu/kanade/tachiyomi/extension/en/readcomicfree/ReadComicFree.kt
> +            // Incredibly ugly, but works
consider using shortcircuit logic to simplify this

2024-04-01 11:36 UTC, AwkwardPeak7 commented on src/en/readcomicfree/src/eu/kanade/tachiyomi/extension/en/readcomicfree/ReadComicFree.kt
> +        val urlBuilder = baseUrl.toHttpUrl().newBuilder()
just use one `.apply` and add everything in there, this way you directly call `addQueryParameter`

2024-04-02 20:20 UTC, barrelltitor commented
Looks like the pages aren't loading now for some reason, checking to see if they changed their css already or if there's something wrong on my end, will reply once that is sorted out. I've made the other changes

2024-04-02 23:14 UTC, barrelltitor commented
All fixed and working!

2024-04-03 12:24 UTC, AwkwardPeak7 commented
This too appears to be WpComics, use the multisrc

2024-05-15 15:38 UTC, closed without merging

2024-05-15 15:38 UTC, AwkwardPeak7 commented
closing due to inactivity, feel free to open a new pull request