TenkaiScan: Change theme
keiyoushi/extensions-source pull request #2211
Opened 2024-04-01 04:47 UTC by bapeey

Closes #2149 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-04-01 08:22 UTC, vetleledaal commented on src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt
>      override val versionId = 2
```suggestion
    override val versionId = 3
```

2024-04-01 14:43 UTC, AwkwardPeak7 requested changes

2024-04-01 14:43 UTC, AwkwardPeak7 commented on src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt
> +        document.selectFirst("div.page-content div.text-details")?.let { element ->
```suggestion
        document.selectFirst("div.page-content div.text-details")!!.let { element ->
```

2024-04-01 14:43 UTC, AwkwardPeak7 commented on src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt
> +    override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
should set thumbnail too

2024-04-02 16:12 UTC, AwkwardPeak7 approved these changes

2024-04-02 16:12 UTC, merged