Add MangaTerra
keiyoushi/extensions-source pull request #2300
Opened 2024-04-08 00:28 UTC by ttony2chopper

Closes #1761

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-04-10 19:08 UTC, vetleledaal commented on src/pt/mangaterra/AndroidManifest.xml
> +                    android:host="manga-terra.com/"
```suggestion
                    android:host="manga-terra.com"
```

2024-04-10 19:08 UTC, vetleledaal commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +            val dom = client.newCall(GET("${document.location()}/${page++}", headers)).execute().asJsoup()
You shouldn't make a new call here for each page, use `imageUrlParse`. If the total page count is unknown you could do a binary search -- could still be slow with the current rate limit.

You can check [Akuma](https://github.com/keiyoushi/extensions-source/blob/2fd542b42b3ab81587bc37568976bc9c8034906c/src/all/akuma/src/eu/kanade/tachiyomi/extension/all/akuma/Akuma.kt#L207) for imageUrlParse
You can check [some older version of MangaHub](https://github.com/kevin01523/tachiyomi-extensions/blob/d292dac0418b4bc90864a54b60c3d7a1c736ead4/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt#L255) for binary search

2024-04-10 19:08 UTC, vetleledaal commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +        if (query.startsWith(slugPrefix)) {
Throws `kotlin.UninitializedPropertyAccessException` for `url` when manually searching for `slug:martial-peak`.

Non-existing slug throws `NullPointerException`, but that's probably fine.

2024-04-11 07:29 UTC, AwkwardPeak7 requested changes

2024-04-11 07:29 UTC, AwkwardPeak7 commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +        )
```suggestion
        val fragment = Jsoup.parseBodyFragment(
            json.decodeFromString<String>(response.body.string()),
            baseUrl,
        )
```

2024-04-11 07:29 UTC, AwkwardPeak7 commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
Please consider grouping methods based on their functionality. Like all popular methods together, then all latest methods and so on

2024-04-12 02:03 UTC, AwkwardPeak7 requested changes

2024-04-12 02:03 UTC, AwkwardPeak7 commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +        setUrlWithoutDomain(document.location())
```suggestion
```

2024-04-12 02:03 UTC, AwkwardPeak7 commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +    }
add a warning/note to tell user to press reset to load the genrelist. also don't add when it is empty

2024-04-12 02:03 UTC, AwkwardPeak7 commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +            .build()
save this outside the function as `noRedirectClient`

2024-04-12 03:43 UTC, ttony2chopper commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +        setUrlWithoutDomain(document.location())
Method call required when searching with ```slug:<manga-id>``` in ```fetchSearchManga```. 

See: https://github.com/keiyoushi/extensions-source/pull/2300/files#r1559936766

But I can change it to set the ``url`` with ``apply`` inline. If that's really the best way.

2024-04-12 03:47 UTC, AwkwardPeak7 commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +        setUrlWithoutDomain(document.location())
Ah, it's fine then

2024-04-12 06:47 UTC, AwkwardPeak7 commented on src/pt/mangaterra/src/eu/kanade.tachiyomi.extension.pt.mangaterra/MangaTerra.kt
> +    private val noRedirectClient = network.client.newBuilder()
use `cloudflareClient`

2024-04-12 14:40 UTC, AwkwardPeak7 approved these changes

2024-04-12 14:41 UTC, merged