Add SenshiManga
keiyoushi/extensions-source pull request #2484
Opened 2024-04-19 03:27 UTC by bapeey

Closes #2466

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-04-19 13:53 UTC, AwkwardPeak7 commented
why make a multisrc with only one source?

2024-04-19 13:59 UTC, bapeey commented
the API returns a different result depending on the site (e.g. https://lat-manga.com/), so I made multisrc just in case

2024-04-19 16:14 UTC, AwkwardPeak7 requested changes

2024-04-19 16:14 UTC, AwkwardPeak7 commented on src/es/senshimanga/src/eu/kanade/tachiyomi/extension/es/senshimanga/SenshiManga.kt
> +    override val client: OkHttpClient = network.client.newBuilder()
use cloudflareClient

2024-04-19 16:14 UTC, AwkwardPeak7 commented on src/es/senshimanga/src/eu/kanade/tachiyomi/extension/es/senshimanga/SenshiManga.kt
> +    override fun headersBuilder(): Headers.Builder = Headers.Builder()
use `super.headersBuilder`

2024-04-19 16:14 UTC, AwkwardPeak7 commented on src/es/senshimanga/src/eu/kanade/tachiyomi/extension/es/senshimanga/SenshiManga.kt
> +    private val organizationDomain = baseUrl.substringAfter("://")
inline this

2024-04-19 16:14 UTC, AwkwardPeak7 commented on src/es/senshimanga/src/eu/kanade/tachiyomi/extension/es/senshimanga/SenshiMangaDto.kt
> +    val data: SeriesListDataDto,
make a template class for data, `Data<T>(val data)`

2024-04-19 16:14 UTC, AwkwardPeak7 commented on src/es/senshimanga/src/eu/kanade/tachiyomi/extension/es/senshimanga/SenshiMangaDto.kt
> +        } catch (_: Exception) {
ParseException

2024-04-20 15:27 UTC, AwkwardPeak7 approved these changes

2024-04-20 15:27 UTC, merged