Add Icons for extension: "PT-BR".
keiyoushi/extensions-source pull request #2572
Opened 2024-04-25 14:11 UTC by nomaxsnx

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-04-25 16:11 UTC, AwkwardPeak7 requested changes
all icons must follow the same convention, **sqaure shaped** with **rounded corners** and **solid background**

2024-04-25 16:11 UTC, AwkwardPeak7 commented on src/pt/ladyestelarscan/res/mipmap-anydpi-v26/ic_launcher.xml
remove

2024-04-25 16:11 UTC, AwkwardPeak7 commented on src/pt/ladyestelarscan/res/mipmap-hdpi/ic_launcher_background.png
use the tool liked in contrubting guide to generate icons

2024-04-25 17:28 UTC, nomaxsnx commented on src/pt/ladyestelarscan/res/mipmap-anydpi-v26/ic_launcher.xml
Done

2024-04-25 17:28 UTC, nomaxsnx commented on src/pt/ladyestelarscan/res/mipmap-hdpi/ic_launcher_background.png
Okay

2024-04-25 17:33 UTC, nomaxsnx commented
> all icons must follow the same convention, **sqaure shaped** with **rounded corners** and **solid background**

Good afternoon, as I'm not very knowledgeable about "Colors", could you tell me which colors are good?

I'll send you a test on commit.

2024-04-25 17:40 UTC, AwkwardPeak7 commented
colour can be any that fit the background, the requirement is for a colour to be present, it can't be transparent.

new akimanga icon is good

2024-04-26 15:54 UTC, vetleledaal commented
Make sure you add padding where it's warranted, currently these seem a bit small:
- flowermanga
- ghostscan
- hentaiteca


Others you touched seem fine:
- akimanga
- amuy
- astrumscans
- cafecomyaoi
- dessertscan
- kakuseiproject


And these are in the wrong shape, but you're actively working on it:
- ladyestelarscan
- leryaoi
- limboscan
- linkstartscan
- maidscan
- mangananquim
- sssscanlator

2024-04-26 16:22 UTC, nomaxsnx commented
> Make sure you add padding where it's warranted, currently these seem a bit small:
> 
> * flowermanga
> * ghostscan
> * hentaiteca


10% Is it OK to apply to everyone?

![image](https://github.com/keiyoushi/extensions-source/assets/157644160/c10e34da-2dca-42d4-838c-ffab9b0b7fd5)

 
![image](https://github.com/keiyoushi/extensions-source/assets/157644160/faf88a91-5388-4c45-959d-4622908665b6)
obs: the logo looks a bit bad because of the text above, I don't know if you cut the text, just leave the ghost or not.

![image](https://github.com/keiyoushi/extensions-source/assets/157644160/df9ac04f-481f-46e9-86f3-e81213625974)

2024-04-26 16:43 UTC, vetleledaal commented
Yes, 10% is good. Usually I try to keep the main subject within the grid lines.

For example:
![image](https://github.com/keiyoushi/extensions-source/assets/13540478/4f4f3ba0-0b8c-448d-a074-0b44c43f09fa)

2024-04-27 08:29 UTC, AwkwardPeak7 approved these changes

2024-04-27 08:33 UTC, merged