Anchira: Fix API changes
keiyoushi/extensions-source pull request #3089
Opened 2024-05-17 17:59 UTC by LetrixZ

#3079

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-05-17 18:01 UTC, LetrixZ commented
I will also take the chance to add the interceptor for images that don't have a resampled option.

Also, there is a new CDN that is used for even page numbers.

2024-05-18 14:44 UTC, AwkwardPeak7 requested changes

2024-05-18 14:44 UTC, AwkwardPeak7 commented on src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt
> +        .add("Origin", "https://anchira.to")
use `baseUrl`

2024-05-18 14:44 UTC, AwkwardPeak7 commented on src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt
> +    private val apiUrl = "https://api.anchira.to"
```suggestion
    private val apiUrl = baseUrl.replace("://", "://api.")
```

2024-05-18 14:56 UTC, AwkwardPeak7 commented on src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt
> +        .add("Origin", "https://anchira.to")
```suggestion
        .add("Referer", "$baseUrl/")
        .add("Origin", baseUrl)
```

2024-05-18 15:06 UTC, AwkwardPeak7 approved these changes

2024-05-18 15:06 UTC, merged