Add FlowerMangaB
keiyoushi/extensions-source pull request #3131
Opened 2024-05-19 14:32 UTC by ttony2chopper

Closes #3054

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-05-20 10:48 UTC, AwkwardPeak7 requested changes
name it `FlowerManga.com` or variant. also rename the other one to include domain tld

2024-05-20 13:33 UTC, ttony2chopper commented
> name it `FlowerManga.com` or variant. also rename the other one to include domain tld

PR:  #3159

2024-05-22 05:24 UTC, AwkwardPeak7 commented
`FlowerManga.com` instead of `(.com)`

2024-05-23 10:52 UTC, AwkwardPeak7 approved these changes

2024-05-23 10:52 UTC, merged