Add TuManhwas
keiyoushi/extensions-source pull request #3285
Opened 2024-05-28 17:56 UTC by ttony2chopper

Closes #3222

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-05-28 18:16 UTC, bapeey commented
Theme not seems like MangaThemesia, it has some of the same selectors and assets names but the structure is very different.

2024-05-28 23:44 UTC, ttony2chopper commented
> Theme not seems like MangaThemesia, it has some of the same selectors and assets names but the structure is very different.
> 
> It seems like they don't even use Wordpress.

I agree, I had to make so many changes that it was simpler not to use the theme

2024-05-29 01:39 UTC, vetleledaal commented
> Theme not seems like MangaThemesia, 

My bad 🤐

Moving it out of the multisrc seems like the right choice

2024-05-30 04:44 UTC, AwkwardPeak7 requested changes

2024-05-30 04:44 UTC, AwkwardPeak7 commented on src/es/tumanhwas/src/eu/kanade/tachiyomi/extension/es/tumanhwas/TuManhwas.kt
> +            .removeSuffix(chapterNumber)
```suggestion
        url = url.replace("news", "manga")
            .substringBeforeLast('-')
```

2024-05-30 04:44 UTC, AwkwardPeak7 commented on src/es/tumanhwas/src/eu/kanade/tachiyomi/extension/es/tumanhwas/TuManhwas.kt
> +                .joinToString()
```suggestion
            genre = it.select(".genres-container a")
                .joinToString { it.text() }
```

2024-05-30 04:44 UTC, AwkwardPeak7 commented on src/es/tumanhwas/src/eu/kanade/tachiyomi/extension/es/tumanhwas/TuManhwas.kt
> +    private val Element.imgSrc: String get() = attr("abs:data-src").ifEmpty { attr("abs:src") }
```
private fun Element.imgAttr(): String {
    return when {
        hasAttr("data-src") -> absUrl("data-src")
        else -> absUrl("src")
    }
}
```
use something like this

2024-05-30 04:44 UTC, AwkwardPeak7 commented on src/es/tumanhwas/src/eu/kanade/tachiyomi/extension/es/tumanhwas/TuManhwas.kt
> +        val number = Regex("""(\d+)""").find(date)?.value?.toIntOrNull() ?: return 0
pull out the regex

2024-05-31 10:58 UTC, AwkwardPeak7 approved these changes

2024-05-31 10:58 UTC, merged