Add filters to Hitomi Extension
keiyoushi/extensions-source pull request #3312
Opened 2024-05-31 06:23 UTC by GoonGooner

Added filters to the Hitomi Extension as it was little barebones. Should be able to use the filter menu for both positive and negative filters, filtering on artists, characters, Groups, Series, Female specific tags, male specific tags, and general tags. Based off a brief ~~goon sesh~~ test, everything seems to be working as expected.

Not a Kotlin cooder so apoligies if I failed to follow an expected style or pattern.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- ~~[ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions~~
- ~~[ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")~~
- ~~[ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate~~
- [x] Have not changed source names
- ~~[ ] Have explicitly kept the `id` if a source's name or language were changed~~
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- ~~[ ] Have removed `web_hi_res_512.png` when adding a new extension~~

2024-05-31 11:12 UTC, AwkwardPeak7 requested changes

2024-05-31 11:12 UTC, AwkwardPeak7 commented on src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
> +    private class OrderFilter(val name: String, val order: OrderType) {
since hitomi class is already too big, move the filter classes to a seperate file.

2024-05-31 11:12 UTC, AwkwardPeak7 commented on src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
> -                    it.replace('_', ' ')
why remove 🤔

2024-05-31 11:12 UTC, AwkwardPeak7 commented on src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
> +                query.append(" ${if (trimmed.startsWith("-")) "-" else ""}$tag:${trimmed.removePrefix("-").replace(" ", "_")}")
consider moving the if condition out for cleaner code

2024-05-31 22:50 UTC, GoonGooner commented on src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
> +    private class OrderFilter(val name: String, val order: OrderType) {
Moved to another file(`Filters.kt`), also moved filter parsing there as well as it felt relevant. Condensed text filters into class as all shared same usage.

2024-05-31 23:01 UTC, GoonGooner commented on src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
> -                    it.replace('_', ' ')
`getGalleryIDsForQuery` function also calls `.replace`, but on the individual query terms, no need to do it twice. Could do it the other way around, keeping the `.map` and not doing it in `getGalleryIDsForQuery`.

Hitomi themselves do it twice (`results.js` L29 and `search.js` L605), which I guess is why we do it twice, but I don't see the reason why.

2024-05-31 23:02 UTC, GoonGooner commented on src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
> +                query.append(" ${if (trimmed.startsWith("-")) "-" else ""}$tag:${trimmed.removePrefix("-").replace(" ", "_")}")
Just moved the if to store in a val instead of doing it in string template. Function moved to `Filters.kt`.

2024-05-31 23:28 UTC, GoonGooner commented
Would there be any interest in a language filter option? Idea being able to search in other languages without having to switch to `all` source and manually typing out `language:<language>` or swapping to the specific language's source. Maybe get rid of factory and add preference screen where user can set default language(defaults to `all` on first install). Probably best to save this for future PR.

I know currently language is gotten from `nozomiLang` or parsed from query input. I would be thinking of a select filter set to default with whatever `nozomiLang` is. I don't think support for multi language input as I couldn't find any on Hitomi, but maybe I'm not searching with the right combination of languages. And if someone needs multi-lang they can still use searchbar and manually make the query.

If a language filter option is wanted and we go with the select filter, is there a way to have it so languages used in factory are shared with languages used by filter. Create array of pairs `<SourceLang: String, nozomiLang: String>`, and use first and second in factory and only use second for language filter? Where to store array as well, in Dto file or hitomi.kt file itself or factory, new file? If we get rid of factory we don't really need to worry about this.

2024-06-01 01:28 UTC, AwkwardPeak7 commented
don't add language filter to language specific source instance. you can add them to only the multi one (`lang = "all"`) if you want

2024-06-01 02:26 UTC, GoonGooner commented
Okay, not going to implement language filter then.

2024-06-01 04:22 UTC, AwkwardPeak7 approved these changes

2024-06-01 04:22 UTC, merged