Akuma Tags Fix
keiyoushi/extensions-source pull request #3390
Opened 2024-06-03 15:19 UTC by KenjieDec

- Removed "Pages" filter — They don't work
- Added "Other Tags" filter
- Added Filter limit warning
- Fixed problem on tags with spaces <sub>( For example: `big penis`. Before:`Male tag contains big. Title contains penis`. After:`Male tag contains big penis` )<sub/>

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-06-03 15:34 UTC, AwkwardPeak7 commented on src/all/akuma/build.gradle
make sure your line endings are `lf`

2024-06-03 15:34 UTC, AwkwardPeak7 commented on src/all/akuma/src/eu/kanade/tachiyomi/extension/all/akuma/Akuma.kt
while you are at it, remove the preference for iconfiied tags, and make it default.

I belive having a preference for such a thing isn't necessary

2024-06-03 15:41 UTC, KenjieDec commented on src/all/akuma/src/eu/kanade/tachiyomi/extension/all/akuma/Akuma.kt
Ok 👍

2024-06-04 05:21 UTC, AwkwardPeak7 commented on src/all/akuma/build.gradle
this file still have different line ending as evident by github showing whole file having difference

2024-06-04 05:22 UTC, AwkwardPeak7 commented on src/all/akuma/src/eu/kanade/tachiyomi/extension/all/akuma/Akuma.kt
> +        filters.forEach { fIt ->
```suggestion
        filters.forEach { filter->
```
since fIt is ambigious imo

2024-06-05 12:16 UTC, AwkwardPeak7 requested changes

2024-06-05 12:16 UTC, AwkwardPeak7 commented on src/all/akuma/src/eu/kanade/tachiyomi/extension/all/akuma/Akuma.kt
> +                    }.parse(client.newCall(chapterListRequest(manga)).execute().asJsoup().select(".date .value>time").text())?.time!!
just remove override for `fetchChapterList` and provide implementation in `chapterListParse` where you will get the response directly

2024-06-05 12:16 UTC, AwkwardPeak7 commented on src/all/akuma/src/eu/kanade/tachiyomi/extension/all/akuma/Akuma.kt
> +                            filter.state.split(",").map {
filter out empty ones, for example user can put 2 commas torgether

2024-06-06 06:30 UTC, AwkwardPeak7 commented on src/all/akuma/src/eu/kanade/tachiyomi/extension/all/akuma/Akuma.kt
> +                }.parse(response.asJsoup().select(".date .value>time").text())?.time!!
move the date format to class val so it doesn't get initialized every time

2024-06-06 11:52 UTC, AwkwardPeak7 approved these changes

2024-06-06 11:52 UTC, merged