Update Spyfakku
keiyoushi/extensions-source pull request #3712
Opened 2024-06-23 05:01 UTC by KenjieDec

Closes #3670 

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-06-23 07:17 UTC, vetleledaal requested changes

2024-06-23 07:17 UTC, vetleledaal commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +                date_upload = dateFormat.parse(doc.selectFirst("p:containsOwn(Released)")!!.parent()!!.selectFirst(".text-sm")!!.ownText())!!.time
Since `date_upload` isn't critical you should avoid using non-null asserts and rather fall back to 0 (or just conditionally set it)

2024-06-23 07:17 UTC, vetleledaal commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +            thumbnail_url = doc.selectFirst("img[src*='/cover']")!!.absUrl("src")
remove non-null assert, value could be missing with site changes

2024-06-23 07:17 UTC, vetleledaal commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +                        dateFormat.parse(doc.selectFirst("p:containsOwn(Released)")!!.parent()!!.selectFirst(".text-sm")!!.ownText())!!.time,
remove non-null assert, value could be missing with site changes

2024-06-23 07:17 UTC, vetleledaal commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +                append("Pages: ", doc.selectFirst("p:containsOwn(pages)")!!.ownText(), "\n")
remove non-null assert, value could be missing with site changes

2024-06-23 21:23 UTC, vetleledaal approved these changes, later dismissed

2024-06-24 15:01 UTC, AwkwardPeak7 requested changes

2024-06-24 15:01 UTC, AwkwardPeak7 commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +                    dateFormat.parse(it)?.time
wrap date parsing around try catch

2024-06-26 11:27 UTC, AwkwardPeak7 requested changes

2024-06-26 11:27 UTC, AwkwardPeak7 commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +        url = "/g/$id"
will the old urls still work? if not then add some logic to handle them in `mangaDetailsRequest` and `chapterListRequest`

2024-06-26 11:27 UTC, AwkwardPeak7 commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +            }
try catch here too

2024-06-26 12:35 UTC, AwkwardPeak7 commented on src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt
> +                url = "/g/${hentai.id}"
same for page list request

2024-06-27 08:21 UTC, AwkwardPeak7 approved these changes

2024-06-27 08:21 UTC, merged