Add mangabtt
keiyoushi/extensions-source pull request #398
Opened 2024-01-19 20:29 UTC by Secozzi

Closes #128

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-01-19 21:31 UTC, vetleledaal requested changes

2024-01-19 21:31 UTC, vetleledaal commented on src/en/mangabtt/src/eu/kanade/tachiyomi/extension/en/mangabtt/MangaBTT.kt
> +            title = text().trim()
`.trim()` is not required after using `.text()`. Comment applies here and elsewhere
https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#text()
> Whitespace is normalized and trimmed.

2024-01-19 21:31 UTC, vetleledaal commented on src/en/mangabtt/src/eu/kanade/tachiyomi/extension/en/mangabtt/MangaBTT.kt
> +            setUrlWithoutDomain(attr("href"))
Might be better to let the HttpSource normalize the URL
```suggestion
            setUrlWithoutDomain(attr("abs:href"))
```

2024-01-19 21:31 UTC, vetleledaal commented on src/en/mangabtt/src/eu/kanade/tachiyomi/extension/en/mangabtt/MangaBTT.kt
> +    private fun parseStatus(status: String?): Int = when {
Consider making this a function under `Element`, as already done with `Element.imgAttr()` for consistency

2024-01-19 21:35 UTC, vetleledaal commented on src/en/mangabtt/src/eu/kanade/tachiyomi/extension/en/mangabtt/MangaBTT.kt
> +            Page(index, document.location(), url)
`url` doesn't seem to be used in `imageRequest()` so you should be able to omit it

```suggestion
            Page(index, imageUrl = url)
```

2024-01-20 10:58 UTC, AwkwardPeak7 approved these changes

2024-01-20 10:58 UTC, merged