LibGroup chapter numbers fix
keiyoushi/extensions-source pull request #4012
Opened 2024-07-14 15:46 UTC by romshke

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-07-14 17:40 UTC, Smol-Ame commented
Write "Closes #3553" in this PR request's description instead, as listed in one of the checklist items

2024-07-15 05:21 UTC, AwkwardPeak7 requested changes

2024-07-15 05:21 UTC, AwkwardPeak7 commented on lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroupDto.kt
> -        chapter_number = itemNumber ?: -1f
remove from dto too if not using

2024-07-16 05:27 UTC, AwkwardPeak7 approved these changes

2024-07-16 05:28 UTC, merged

2024-07-16 06:48 UTC, BlueCat300 commented
After this update app crashes during global(all sources) search manga.

2024-07-16 06:58 UTC, Smol-Ame commented
> After this update app crashes during global(all sources) search manga.

@BlueCat300 could you come to the Keiyoushi Discord repo-support channel to provide some extra info? At least on my end with a fresh extension install, it doesn't seem to crash