Add Hachi
keiyoushi/extensions-source pull request #4078
Opened 2024-07-17 19:24 UTC by vetleledaal

Tried adding filters, gave up. Releasing as-is as I can't dedicate too much time fucking around with it.

There are some duplicate lines, especially around popular/latest/search-request and search/details-parse. I also left all fields in the DTOs, except for `__NEXT_DATA__`. Let me know if this is unacceptable.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-07-18 11:01 UTC, AwkwardPeak7 requested changes

2024-07-18 11:01 UTC, AwkwardPeak7 commented on src/en/hachi/src/eu/kanade/tachiyomi/extension/en/hachi/Hachi.kt
> +                url = "$baseUrl/article/${manga.link}"
save relative urls or just the id/slug

2024-07-18 11:01 UTC, AwkwardPeak7 commented on src/en/hachi/src/eu/kanade/tachiyomi/extension/en/hachi/Hachi.kt
> +                url = "$baseUrl/article/${dto.pageProps.article.link}/chapter/${chapter.chapterNumber.toPrettyString()}"
same here

2024-07-18 11:01 UTC, AwkwardPeak7 commented on src/en/hachi/src/eu/kanade/tachiyomi/extension/en/hachi/Hachi.kt
> +        this.toString().trimEnd('0').removeSuffix(".")
```suggestion
        toString().removeSuffix(".0")
```

2024-07-18 11:01 UTC, AwkwardPeak7 commented on src/en/hachi/src/eu/kanade/tachiyomi/extension/en/hachi/HachiDto.kt
I would say only serialize necessary fields

2024-07-18 19:51 UTC, vetleledaal commented on src/en/hachi/src/eu/kanade/tachiyomi/extension/en/hachi/Hachi.kt
> +                url = "$baseUrl/article/${manga.link}"
Opted for relative URLs, as that's easier to work with when it comes to the URL intent filter.

2024-07-18 19:55 UTC, vetleledaal commented on src/en/hachi/src/eu/kanade/tachiyomi/extension/en/hachi/HachiDto.kt
Commented out the unused fields, that way it won't error out if those are missing.

Commented out instead of removing to avoid redoing the work in the future.

2024-07-19 05:47 UTC, AwkwardPeak7 approved these changes

2024-07-19 05:47 UTC, merged