Fix AsuraScans
keiyoushi/extensions-source pull request #4198
Opened 2024-07-24 00:05 UTC by bapeey

Draft for review, some things are missing

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-07-24 06:07 UTC, lamaxama commented
Thank you for your work. I've tested it, and it works. Since dynamic URLs have been added, can we further add an interceptor to handle the 404 case and automatically migrate, like [MangaThemesiaAlt](https://github.com/keiyoushi/extensions-source/blob/682afcabce4353c281e53fc2319ee5c826613d05/lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaAlt.kt#L152)? In that scenario, most users won't need to migrate a ton of titles in the library.

2024-07-24 06:19 UTC, hemanthmannam reviewed
All good

2024-07-24 07:55 UTC, Lygaen reviewed
Works for me as well!

2024-07-24 08:46 UTC, Lygaen commented
It seems that adding might just work, I'll try it on my machine

```kt

        .addInterceptor { chain ->
            val request = chain.request()
            val response = chain.proceed(request)

            if (!response.isSuccessful && response.code == 404) {
                response.close()

                val dynUrl = request.url.toString().toDynamicUrlIfNeeded()

                val newRequest = request.newBuilder()
                    .url(dynUrl)
                    .build()

                return@addInterceptor chain.proceed(newRequest)
            }

            return@addInterceptor response
        }

```

2024-07-24 09:10 UTC, hemanthmannam commented
Someone please approve this

2024-07-24 09:13 UTC, Lygaen commented
> It seems that adding might just work, I'll try it on my machine
> 
> ```kotlin
>         .addInterceptor { chain ->
>             val request = chain.request()
>             val response = chain.proceed(request)
> 
>             if (!response.isSuccessful && response.code == 404) {
>                 response.close()
> 
>                 val dynUrl = request.url.toString().toDynamicUrlIfNeeded()
> 
>                 val newRequest = request.newBuilder()
>                     .url(dynUrl)
>                     .build()
> 
>                 return@addInterceptor chain.proceed(newRequest)
>             }
> 
>             return@addInterceptor response
>         }
> ```

It works ! Manual intervention for migration will be required nonetheless but at least the interceptor works.

The migration will need to be done manually because the mangas reference a deleted extension on update, so, even with an interceptor, users will need to migrate manually

2024-07-24 09:13 UTC, Smol-Ame commented
> Someone please approve this

Don't rush, all the work is done by volunteers using their own time. Wait for it to be reviewed/approved, or migrate to a different source.

2024-07-24 09:19 UTC, liven-maksim-infotecs commented
> users will need to migrate manually

What do you mean by that? 
1. by using migration button 
2. add new version of manga manually and than remove old one

2024-07-24 09:20 UTC, Lygaen commented
No they will need to push the migrate button

2024-07-24 12:04 UTC, AwkwardPeak7 reviewed
I am still iffy on the URL situation. Maybe save the slug only in the dB and handle rest of the URL through the pref map. Also would it be possible to get all series slug from the API or something? (Kinda like old HeanCMS impl). We can further discuss in discord.

2024-07-24 12:04 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
>      init {
This won't work as the id will have changed, you can directly delete the old shared pref by hard coding the old id.

2024-07-24 12:11 UTC, MaxLevs commented
> I am still iffy on the URL situation. Maybe save the slug only in the dB and handle rest of the URL through the pref map. 

But nothing will change if they not only change the base url. If changes in url path occur, then code modifications need to be done.

2024-07-24 12:58 UTC, lamaxama commented
@bapeey  Hey, I added the automatic migration feature based on your modifications. It has been tested, and most titles can be migrated automatically.  https://github.com/lamaxama/extensions-source/commit/0c9e4806c8f7eb5e82be6eb802f0531771a402d6
If possible, you can simply copy the code. I just don't want to migrate tons of titles in the library.

Additionally, the new site will automatically redirect https://asuracomic.net/series/the-lords-coins-arent-decreasing-123456 to https://asuracomic.net/series/the-lords-coins-arent-decreasing-86df2251. Therefore, having a search base dynamic URL may not be necessary.

2024-07-24 13:01 UTC, 1aam2am1 commented
Old: https://asuracomic.net/manga/1908287720-martial-god-regressed-to-level-2/
New: https://asuracomic.net/series/martial-god-regressed-to-level-2-ce6b06dd

I don't think we can do anything in this case.
We could try saving it as 'Permament manga url'/only webpage or series name as key.

But it won't work if they are changing it so much.
So I think we can try adding some way so user can change domain url. Or that plugin will try to work with single redirection.

However this should be discussion after delivering the fix. We can try future proof the plugin so in the next site change, the migration wouldn't be needed. But that's it.

2024-07-24 13:06 UTC, MaxLevs commented
> Or that plugin will try to work with single redirection.

They are redirecting to the '/' if I recall correctly

2024-07-24 19:42 UTC, bapeey commented
@lamaxama i added a similar workaround for auto migration, can you test?

2024-07-24 23:00 UTC, lamaxama commented
@bapeey It works! Truly a clever approach! One more thing, we can now remove this line: Injekt.get().getSharedPreferences("source_6247824327199706550", 0x0000), because we have not changed the versionId.

2024-07-25 04:00 UTC, AhYOh69 commented
I don't understand anything at all but it looks cool... So when and where can we download the extension 🥹?

2024-07-25 04:09 UTC, bellfireg commented
> I don't understand anything at all but it looks cool... So when and where can we download the extension 🥹?

just wait and see . they still working on it using their time . you just need to wait.

2024-07-25 04:17 UTC, zephyrxk commented
How to do this still showing no results found
![Uploading Screenshot_20240725_121708_Mihon.jpg…]()

2024-07-25 04:24 UTC, zephyrxk commented
> > I don't understand anything at all but it looks cool... So when and where can we download the extension 🥹?
> 
> just wait and see . they still working on it using their time . you just need to wait.

Is it still not fixed the asura scan opening?

2024-07-25 08:38 UTC, Thaafisilt commented
I never felt so dumb in my life until I saw what was happening here. It's like my brain went on vacation without telling me!

2024-07-25 08:59 UTC, Gamermemer commented
> I never felt so dumb in my life until I saw what was happening here. It's like my brain went on vacation without telling me!

Very very true, now just waiting for this God's man to fix the repo

2024-07-25 09:02 UTC, Smol-Ame commented
Can everybody not comment here if you aren't contributing? This pings the server channel & emails everyone in this pull request.

Wait for a fix, and if you need to discuss how badly you want the fix, do it in the Keiyoushi Discord repo-support channel instead.

2024-07-25 09:25 UTC, AwkwardPeak7 requested changes

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +    }
`mangaDetailsRequest` builds same(?) url so no need to override

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +        thumbnail_url = document.selectFirst("img[alt=poster]")!!.attr("abs:src")
no need to add `!!` to non-essential fields

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +    }
same here

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +            return slugMap.getOrNull()?.toMutableMap() ?: mutableMapOf()
```suggestion
            return try {
                json.decodeFromString<Map<String, String>>(jsonMap).toMutableMap()
            } catch (_: Exception) {
                mutableMapOf()
            }
```

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +        private val OLD_FORMAT_MANGA_REGEX = """^/manga/\d*(.*?)/?$""".toRegex()
/manga/1223-cool-manga/
/manga/cool-manga/

```suggestion
        private val OLD_FORMAT_MANGA_REGEX = """^/manga/(\d+-)?([^/]+)/?$""".toRegex()
```

would have to adjust the match group elsewhere in the code too

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +        private val OLD_FORMAT_CHAPTER_REGEX = """^/\d+-[^/]*-chapter-\d+(-\d+)*/?$""".toRegex()
```suggestion
        private val OLD_FORMAT_CHAPTER_REGEX = """^/(\d+-)?[^/]*-chapter-\d+(-\d+)*/?$""".toRegex()
```
similar here

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +        private const val PREF_DYNAMIC_URL_SUMMARY = "Automatically update random numbers in manga URLs.\nHelps mitigating HTTP 404 errors during update and \"in library\" marks when browsing.\nNote:
inline these

2024-07-25 09:25 UTC, AwkwardPeak7 commented on src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt
> +        thumbnail_url = element.selectFirst("img")!!.attr("abs:src")
```suggestion
        thumbnail_url = element.selectFirst("img")?.attr("abs:src")
```

2024-07-25 11:11 UTC, uChieLs commented
> Works for me as well!
 
i'm sorry , i'm new and searching how to solve asura scan no result found .
can please explain how to solve it ?
i read from top to bottom but i can't understand how to .
sorry for my bad english and thanks .

2024-07-25 11:15 UTC, Norsze commented
This is an ongoing development of the extension, if you don't have anything to contribute to the effort with programming knowledge, then please don't comment here, you won't get help here. This section is for helping the development.

2024-07-25 15:52 UTC, AwkwardPeak7 approved these changes

2024-07-25 15:54 UTC, merged