AnimeSama: Add support for multiple scan versions (#4156)
keiyoushi/extensions-source pull request #4325
Opened 2024-07-29 12:47 UTC by CriosChan

Closes #4156

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-07-30 07:32 UTC, AwkwardPeak7 requested changes

2024-07-30 07:32 UTC, AwkwardPeak7 commented on src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt
> +            val page = client.newCall(fetchExistentSubMangas).execute()
this will result in n calls for n manga, please avoid this.

2024-07-30 18:05 UTC, CriosChan commented on src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt
> +            val page = client.newCall(fetchExistentSubMangas).execute()
Would it be ok to limit the number of manga using the page system? I was also thinking about the possibility of making scanlators?

2024-07-31 07:37 UTC, AwkwardPeak7 commented on src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt
> +            val page = client.newCall(fetchExistentSubMangas).execute()
Pagination is an option but please avoid making individual calls for each manga in browse. 
I don't follow what you mean by scanlators? You can add them to chapters of that what you are asking

2024-08-01 08:02 UTC, AwkwardPeak7 requested changes

2024-08-01 08:02 UTC, AwkwardPeak7 commented on src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt
>      override fun chapterListRequest(manga: SManga): Request {
request methods should ideally only return a request, you can make more requests in the parse method

2024-08-02 10:32 UTC, AwkwardPeak7 approved these changes

2024-08-02 10:32 UTC, merged