Reaper Scans: Update to new website
keiyoushi/extensions-source pull request #4359
Opened 2024-07-31 09:54 UTC by webmsgr

Closes #4356
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-07-31 12:07 UTC, AwkwardPeak7 requested changes

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +    override fun popularMangaRequest(page: Int): Request = GET("https://api.reaperscans.com/query?page=$page&perPage=20&series_type=Comic&query_string=&order=desc&orderBy=total_views&adult=true", hea
save `apiUrl` variable in the class instead of repeating it multiple times

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request = GET("https://api.reaperscans.com/query?page=$page&perPage=20&series_type=Comic&query_string=${query.repla
use `HttpUrl.Builder` to encode the query properly.

also there are filters on the site, will you consider implementing them? (you don't have to just asking)

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +                url = "/series/${it.slug}"
are old urls compatible with new ones? if not bump the `versionId` in the class

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +        return GET("https://api.reaperscans.com/chapter/query?page=1&perPage=30&series_id=$seriesId", headers)
please don't...
save the id in the url as fragment during browse. (bump versionId too)
`/series/$slug#$id`

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +            } else {
just put `perPage=9999` and don't worry about it. (unless it doesn't work?)

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +            }
use the `imgAttr()` function available in the class

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
>      private fun randomString(length: Int): String {
remove unnecessary functions which are not used anymore

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +
inherit from `HttpSource` instead of `ParsedHttpSource`

2024-07-31 12:07 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScansDto.kt
> +data class MetaDto(
use regular classes, data classes are not necessary

2024-07-31 12:12 UTC, AwkwardPeak7 commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
>      override fun mangaDetailsParse(document: Document): SManga {
there is an endpoint for details too
`$apiUrl/series/$slug`
`https://api.reaperscans.com/series/ghost-story-club-remake`

2024-08-01 00:28 UTC, webmsgr commented
Hold off on merging this, found a chapter data endpoint with page urls.

2024-08-01 00:56 UTC, bapeey commented
Isn't the theme [HeanCMS](https://github.com/keiyoushi/extensions-source/blob/55b4a3dbecacc8a67286059f73093e2fe6592d73/lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt)?

2024-08-01 08:06 UTC, AwkwardPeak7 commented on src/en/reaperscans/build.gradle
> +    overrideVersionCode = 50
heancms base version is 25, so adjust the override version accordingly

2024-08-02 10:33 UTC, AwkwardPeak7 approved these changes

2024-08-02 10:33 UTC, merged