HiperCool change Url
keiyoushi/extensions-source pull request #447
Opened 2024-01-21 14:53 UTC by deividgabrielpeira

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension
- [X] Updated the extension url

2024-01-21 17:37 UTC, vetleledaal requested changes
Also, combining multiple changes like this makes it harder to review.
Seems like all remaining icons were properly deleted.


Changes:
Cerise Scan (pt-BR): https://cerisescan.com -> https://cerisescan.net
HipercooL (pt-BR): https://hipercool.xyz -> https://hiper.cool
Arkham Scan (pt-BR): deleted, replaced by Hunters Scan (pt-BR) (existing extension)
SSS Hentais (pt-BR): deleted (Closes #426)
AnimaRegia (pt-BR): deleted (Closes #428)

2024-01-21 17:37 UTC, vetleledaal commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("Cerise Scan", "https://cerisescan.net", "pt-BR", pkgName = "cerisescans", isNsfw = true, overrideVersionCode = 7),
You need to bump the version when updating extensions.
```suggestion
        SingleLang("Cerise Scan", "https://cerisescan.net", "pt-BR", pkgName = "cerisescans", isNsfw = true, overrideVersionCode = 8),
```

2024-01-21 17:37 UTC, vetleledaal commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("HipercooL", "https://hiper.cool", "pt-BR", isNsfw = true, className = "Hipercool"),
```suggestion
        SingleLang("HipercooL", "https://hiper.cool", "pt-BR", isNsfw = true, className = "Hipercool", overrideVersionCode = 1),
```

2024-01-21 17:58 UTC, deividgabrielpeira commented
> Also, combining multiple changes like this makes it harder to review. Seems like all remaining icons were properly deleted.
> 
> Changes: Cerise Scan (pt-BR): https://cerisescan.com -> https://cerisescan.net HipercooL (pt-BR): https://hipercool.xyz -> https://hiper.cool Arkham Scan (pt-BR): deleted, replaced by Hunters Scan (pt-BR) (existing extension) SSS Hentais (pt-BR): deleted (Closes #426) AnimaRegia (pt-BR): deleted (Closes #428)

Thanks

2024-01-22 02:53 UTC, beerpiss approved these changes

2024-01-22 02:57 UTC, deividgabrielpeira commented
Please don't accept the pr, tomorrow I'll delete some extensions that don't work anymore.

2024-01-22 04:02 UTC, beerpiss commented
> Please don't accept the pr, tomorrow I'll delete some extensions that don't work anymore.

Then make a new pull request for it. Vetle already recommended you to make **one PR for each extension.**

2024-01-22 04:02 UTC, merged