LeerCapitulo: Fix script not found
keiyoushi/extensions-source pull request #4627
Opened 2024-08-14 17:32 UTC by bapeey

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-08-14 20:36 UTC, vetleledaal requested changes

2024-08-14 20:36 UTC, vetleledaal commented on src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt
> +    private val notRateLimitClient = network.cloudflareClient.newBuilder().build()
```suggestion
    private val notRateLimitClient = network.cloudflareClient
```

Should be the same unless I'm missing some subtle difference.

2024-08-14 20:36 UTC, vetleledaal commented on src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt
> +            val scriptData = notRateLimitClient.newCall(GET(script.attr("abs:src"), headers)).execute().body.string()
Would it make sense to cache this for a short while, like the index of the correct script? Not as in filtering out, but rather changing the order scripts are requested.

2024-08-15 04:17 UTC, AwkwardPeak7 approved these changes

2024-08-15 04:18 UTC, merged