Manhwabuddy
keiyoushi/extensions-source pull request #4810
Opened 2024-08-28 12:31 UTC by dngonz

Closes #4809

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-08-28 19:42 UTC, vetleledaal requested changes

2024-08-28 19:42 UTC, vetleledaal commented on src/en/manhwabuddy/src/eu/kanade/tachiyomi/extension/en/manhwabuddy/ManhwaBuddy.kt
> +    override val baseUrl = "https://manhwabuddy.com/"
Remove trailing slash

2024-08-28 19:42 UTC, vetleledaal commented on src/en/manhwabuddy/src/eu/kanade/tachiyomi/extension/en/manhwabuddy/ManhwaBuddy.kt
> +            date_upload = element.selectFirst(".ct-update")?.text()?.let { parseDate(it) }!!
`date_upload` isn't critical, you should not use a non-null assert here.

2024-08-28 19:42 UTC, vetleledaal commented on src/en/manhwabuddy/src/eu/kanade/tachiyomi/extension/en/manhwabuddy/ManhwaBuddy.kt
> +            thumbnail_url = element.selectFirst("img")!!.attr("src")
Not critical, remove non-null assert.

Comment also applies to wherever you have set `thumbnail_url` throughout this file.

2024-08-28 19:42 UTC, vetleledaal commented on src/en/manhwabuddy/src/eu/kanade/tachiyomi/extension/en/manhwabuddy/ManhwaBuddy.kt
> +    }
Functions that return a string can generally be simplified.
```suggestion
    override fun chapterListSelector(): String = ".chapter-list a"
```

Comment also applies to similar patterns used throughout this file.

2024-08-28 19:42 UTC, vetleledaal commented on src/en/manhwabuddy/src/eu/kanade/tachiyomi/extension/en/manhwabuddy/ManhwaBuddy.kt
> +            artist = info.selectFirst("li:contains(Artist(s)) a")?.text()
Does Jsoup properly tokenize the selector here? To be on the safe side, consider:
```css
li:contains(Artist) a
```

2024-08-28 19:44 UTC, vetleledaal commented
For future reference, you don't need a corresponding issue for each PR. If there are no related issues it means you have linked all related issues (none).

2024-08-29 06:05 UTC, dngonz commented
Hi @vetleledaal thanks for the review, changes are already applied, also added a new change just to improve the description.

2024-08-29 08:16 UTC, AwkwardPeak7 commented on src/en/manhwabuddy/res/output-onlinepngtools.png
remove

2024-08-29 09:17 UTC, vetleledaal approved these changes

2024-08-30 11:11 UTC, AwkwardPeak7 approved these changes

2024-08-30 11:11 UTC, merged