Add Bega Translation, bump Madara theme
keiyoushi/extensions-source pull request #5027
Opened 2024-09-13 08:01 UTC by Smol-Ame

Closes #5007 

* Add Bega Translation (ES)
 * I think it uses newChapterEndpoint, please advise if incorrect
* Bumped Madara theme
 * Added "Publicándose" to Madara theme Ongoing strings

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-09-13 08:23 UTC, AwkwardPeak7 requested changes

2024-09-13 08:23 UTC, AwkwardPeak7 commented on src/es/begatranslation/src/eu/kanade/tachiyomi/extension/es/begatranslation/BegaTranslation.kt
> +    override val mangaSubString = "mangas"
```suggestion
    override val mangaSubString = "series"
```
generally mangasubeting is from the manga path => `https://begatranslation.com/series/cool-manga/`

2024-09-13 08:23 UTC, AwkwardPeak7 commented on lib-multisrc/madara/build.gradle.kts
> +baseVersionCode = 37
you can avoid bumping madara for this

2024-09-13 08:25 UTC, AwkwardPeak7 commented
> Also, any easy way to nab mangaDetails cover to replace slightly low-res Popular/Browse?

you can try writing an interceptor to remove `widthxheight` at end of url

2024-09-13 13:20 UTC, vetleledaal commented
> * I think it uses newChapterEndpoint, please advise if incorrect

If you have set it to true it won't even try the old method, so it working means it's fine.

> * Also, any easy way to nab mangaDetails cover to replace slightly low-res Popular/Browse?

override `popularMangaFromElement`, call the super method, and replace width/height. Something like:

https://github.com/keiyoushi/extensions-source/blob/6e79ac8a9abbbff223b82112365f9d65b32fe5cb/src/ja/mangarawplus/src/eu/kanade/tachiyomi/extension/ja/mangarawplus/MangaRawPlus.kt#L21-L25

2024-09-13 18:34 UTC, vetleledaal approved these changes

2024-09-14 06:00 UTC, AwkwardPeak7 approved these changes

2024-09-14 06:01 UTC, merged