TeamLanhLung: Update domain
keiyoushi/extensions-source pull request #5119
Opened 2024-09-19 01:52 UTC by choppeh

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-09-20 07:19 UTC, AwkwardPeak7 approved these changes

2024-09-20 07:20 UTC, AwkwardPeak7 requested changes
conflicts

2024-09-20 08:43 UTC, axewriter commented
Actually the domain was updated to teamlanhlungday.blog

2024-09-22 06:39 UTC, AwkwardPeak7 approved these changes

2024-09-22 06:39 UTC, merged