Zaimanhua: fix image url expire problem
keiyoushi/extensions-source pull request #5455
Opened 2024-10-09 15:59 UTC by zhongfly

Close #5414 

Image links are valid for 180 seconds.
To avoid using expired image links, each image will request the api to get the link but the request will be cached for 180 seconds to reduce the network load.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-10-09 16:52 UTC, zhongfly commented
In some specific cases, the image was not downloaded immediately after calling fetchImageUrl (e.g., the user interrupted reading or cancels the download). If the same chapter open/download again, the imageUrls of these images is expired and will always fail to load.
And it is difficult to back out the request parameters used in fetchImageUrl through the expired imageUrl, which also makes the idea of intercepting the image load failure and then re-fetching the image link difficult to realize.

I've decided to ignore this extreme situation for now.

2024-10-11 11:22 UTC, AwkwardPeak7 requested changes

2024-10-11 11:22 UTC, AwkwardPeak7 commented on src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt
> +    }
consider using combination of `imageUrlRequest` and `ImageUrlParse` instead

2024-10-11 11:24 UTC, AwkwardPeak7 commented
>  And it is difficult to back out the request parameters used in fetchImageUrl through the expired imageUrl, which also makes the idea of intercepting the image load failure and then re-fetching the image link difficult to realize.

have you tried saving the request parms etc in the image url fragment (maybe as a json string) and using okhttp interceptors instead?

2024-10-11 11:27 UTC, zhongfly commented on src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt
> +    }
In `ImageUrlParse`, `page.index` is invalid.

2024-10-11 14:18 UTC, zhongfly commented
> have you tried saving the request parms etc in the image url fragment (maybe as a json string) and using okhttp interceptors instead?

Done

2024-10-12 07:21 UTC, AwkwardPeak7 commented on src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt
> +            throw Exception(result.errmsg)
only throw `IOException` from interceptors

2024-10-12 10:43 UTC, zhongfly commented on src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt
> +            throw Exception(result.errmsg)
fixed

2024-10-13 01:33 UTC, AwkwardPeak7 approved these changes

2024-10-13 01:33 UTC, merged