Update GenZToons URL
keiyoushi/extensions-source pull request #5462
Opened 2024-10-10 21:06 UTC by lavavex

Fixes #5445

Checklist:

- [N/A ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ Y] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ Y] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [N/A ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ Y] Have not changed source names
- [ Y] Have explicitly kept the `id` if a source's name or language were changed
- [ Y] Have tested the modifications by compiling and running the extension through Android Studio
- [ N/A] Have removed `web_hi_res_512.png` when adding a new extension

2024-10-10 21:42 UTC, Smol-Ame commented
No trailing slash for the baseUrls (test again to make sure it works)

Also, just put x in the checkboxes (example: [x] instead of "Y" so it actually checkmarks it (and leave the non-applicable ones as empty).

2024-10-11 11:26 UTC, AwkwardPeak7 requested changes
remove trailing slash as stated previosuly

2024-10-11 11:26 UTC, AwkwardPeak7 commented
the old url is working fine for me...?

2024-10-11 17:01 UTC, shabnix commented
The old URL still works, but newer chapters are no longer added to the old website. There is just a single image with "new chapters is now available at genzupdates.com"

![Screenshot_2024-10-11-18-59-33-55_551f7f0ca926862b368845ce7ee433aa.jpg](https://github.com/user-attachments/assets/afe64aa8-9aed-45bd-901d-7605f45d787d)

2024-10-12 04:32 UTC, lavavex reviewed
Yes, sorry for missing that

2024-10-13 19:38 UTC, AwkwardPeak7 commented
new domain is on Keyoapp

2024-10-13 19:38 UTC, closed without merging