Add InovaScanManga
keiyoushi/extensions-source pull request #5502
Opened 2024-10-12 21:49 UTC by Starmania

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-10-13 01:54 UTC, AwkwardPeak7 requested changes

2024-10-13 01:54 UTC, AwkwardPeak7 commented on src/fr/inovascanmanga/src/eu/kanade/tachiyomi/extension/fr/inovascanmanga/InovaScanManga.kt
set `useNewChapterEndpoint` to true

![image](https://github.com/user-attachments/assets/c564317d-a6a7-4dc1-ab82-c27dd203bc1a)
`/ajax/chapters` in the devtool means new chapter endpoint

2024-10-13 14:17 UTC, vetleledaal requested changes
Some titles on the popular and latest tabs have no name. This indicates a faulty selector, or duplicate URLs. To fix it I would first look into `popularMangaSelector()` and `popularMangaUrlSelector`.

Author and description is not set, please add some selectors for that.

(Status is always unknown, but that's missing from the site -- so nothing you can do about it.)

2024-10-13 14:17 UTC, vetleledaal commented on src/fr/inovascanmanga/src/eu/kanade/tachiyomi/extension/fr/inovascanmanga/InovaScanManga.kt
> +    SimpleDateFormat("dd MMMMMM yyyy", Locale.FRENCH),
```suggestion
    SimpleDateFormat("dd MMMM yyyy", Locale.FRENCH),
```

2024-10-13 14:17 UTC, vetleledaal commented on src/fr/inovascanmanga/src/eu/kanade/tachiyomi/extension/fr/inovascanmanga/InovaScanManga.kt
Along the same lines, you could also set this ~to skip another request~:
```kt
override val useLoadMoreRequest = LoadMoreStrategy.Always
```

2024-10-13 14:17 UTC, vetleledaal commented on src/fr/inovascanmanga/res/mipmap-xxxhdpi/ic_launcher.png
Make sure you use the highest quality icon (https://inovascanmanga.com/wp-content/uploads/2024/02/new-logo.png)

As for this icon, I think 0 padding would fit better. Make sure you still keep a closeish background color, as it might show slightly on the edges.

2024-10-13 15:41 UTC, Starmania commented on src/fr/inovascanmanga/res/mipmap-xxxhdpi/ic_launcher.png
I had difficulties to found it, thanks you !

2024-10-14 01:31 UTC, Starmania commented
This should be good (tested with current values) but I'm double checking that there is no status for real

2024-10-14 11:44 UTC, AwkwardPeak7 approved these changes

2024-10-14 11:44 UTC, merged