MeituaTop: Re-add extension with updated domain
keiyoushi/extensions-source pull request #5556
Opened 2024-10-17 03:03 UTC by dangobruh

source wrongly removed #4951 as it is not dead
downloaded files from old repo and updated domain+version
sorry for any mistakes i may have made

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-10-17 05:19 UTC, vetleledaal commented on src/all/meituatop/build.gradle
> +    extVersionCode = 7
You don't need to bump the version if you're not changing anything. Although that's hard to tell through GitHub's UI.

2024-10-18 12:50 UTC, AwkwardPeak7 requested changes

2024-10-18 12:50 UTC, AwkwardPeak7 commented on src/all/meituatop/src/eu/kanade/tachiyomi/extension/all/meituatop/MeituaTop.kt
> +    override val baseUrl = "https://88188.meitu.lol/"
```suggestion
    override val baseUrl = "https://88188.meitu.lol"
```

2024-10-28 10:03 UTC, AwkwardPeak7 approved these changes

2024-10-28 10:04 UTC, merged