Add TruyenGG
keiyoushi/extensions-source pull request #5687
Opened 2024-10-24 23:54 UTC by dejavui

Checklist:
Closes #5461
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-10-25 21:33 UTC, vetleledaal requested changes

2024-10-25 21:33 UTC, vetleledaal commented on src/vi/truyengg/build.gradle
> +    extVersionCode = 0
CI is failing here
```suggestion
    extVersionCode = 1
```

2024-10-25 21:33 UTC, vetleledaal commented on src/vi/truyengg/src/eu/kanade/tachiyomi/extension/vi/truyengg/TruyenGG.kt
> +        setUrlWithoutDomain(element.select("a").attr("href"))
Use `.selectFirst()` when applicable. Comment applies throughout this file. Using `.select()` is less performant (not that important) and will select all elements which may lead to unintended behavior.

2024-10-27 07:05 UTC, AwkwardPeak7 commented on src/vi/truyengg/src/eu/kanade/tachiyomi/extension/vi/truyengg/TruyenGG.kt
> +        .build()
```suggestion
        .retryOnConnectionFailure(true)
        .rateLimit(1)
        .build()
```
the others are default behavior on tachi/mihon.

2024-10-27 07:05 UTC, AwkwardPeak7 commented on src/vi/truyengg/src/eu/kanade/tachiyomi/extension/vi/truyengg/TruyenGG.kt
> +        .retryOnConnectionFailure(true)
why?

2024-11-04 13:09 UTC, AwkwardPeak7 approved these changes

2024-11-04 13:09 UTC, merged