Added MangaRuhu extension for Turkish manga source.
keiyoushi/extensions-source pull request #5830
Opened 2024-11-02 01:27 UTC by Forza06

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-11-03 09:53 UTC, vetleledaal requested changes

2024-11-03 09:53 UTC, vetleledaal commented on src/tr/mangaruhu/build.gradle
> +    overrideVersionCode = 1
```suggestion
    overrideVersionCode = 0
```

2024-11-03 09:53 UTC, vetleledaal commented on src/tr/mangaruhu/res/mipmap-xxxhdpi/ic_launcher.png
Please use the icon generator mentioned in the [contributing guidelines](https://github.com/keiyoushi/extensions-source/blob/6577a20ead5ab7896aa5349602652c38bf657e4f/CONTRIBUTING.md#tools).

2024-11-03 09:53 UTC, vetleledaal commented on src/tr/mangaruhu/src/eu/kanade/tachiyomi/extension/tr/mangaruhu/MangaRuhu.kt
> +    SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH),
Date format doesn't seem to match site. Is the API returning a different format?

Try:
```suggestion
    SimpleDateFormat("d MMMM yyyy", Locale("tr")),
```

2024-11-04 02:11 UTC, Forza06 commented on src/tr/mangaruhu/res/mipmap-xxxhdpi/ic_launcher.png
I already used the icon generator in contributing guidelines I just changed the Shape value to none

2024-11-04 13:15 UTC, AwkwardPeak7 commented on src/tr/mangaruhu/res/mipmap-xxxhdpi/ic_launcher.png
icon shape should be square with rounded corners

2024-11-05 15:54 UTC, Forza06 commented on src/tr/mangaruhu/res/mipmap-xxxhdpi/ic_launcher.png
I changed the icons to square

2024-11-07 11:16 UTC, AwkwardPeak7 approved these changes

2024-11-07 11:16 UTC, merged