Add InfinityXScan
keiyoushi/extensions-source pull request #6407
Opened 2024-12-01 00:27 UTC by Creepler13

Closes: #6334

Checklist:

- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Have not changed source namesurce's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [X] Have removed `web_hi_res_512.png` when adding a new extension

2024-12-01 02:05 UTC, vetleledaal requested changes

2024-12-01 02:05 UTC, vetleledaal commented on src/pt/infinyxscan/src/eu/kanade/tachiyomi/extension/pt/infinyxscan/InfinyxScan.kt
> +    "https://infinyxscan.cloud/",
Remove trailing slash here and in build file

2024-12-01 02:05 UTC, vetleledaal commented on src/pt/infinyxscan/build.gradle
> +apply from: "$rootDir/common.gradle"
Missing trailing newline

2024-12-01 12:40 UTC, vetleledaal commented on src/pt/infinyxscan/build.gradle
> +
Too many newlines.

2024-12-03 13:16 UTC, AwkwardPeak7 approved these changes

2024-12-03 13:17 UTC, merged