Add KadoComi (Comic Walker)
keiyoushi/extensions-source pull request #6473
Opened 2024-12-05 02:44 UTC by hatozuki-programmer

Closes #5422 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

2024-12-05 04:43 UTC, bapeey commented
Consider using `kotlinx.serialization` with DTO's instead of `org.json`

2024-12-05 20:13 UTC, vetleledaal requested changes

2024-12-05 20:13 UTC, vetleledaal commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +                SERIALIZATION_UNKNOWN -> SManga.UNKNOWN
You can just inline the 2 strings.

2024-12-05 20:13 UTC, vetleledaal commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        return list.joinToString(", ")
`, ` is the default

2024-12-05 20:13 UTC, vetleledaal commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        val episodeCode = params[1].split("=")[1]
Use `chapter.url.toHttpUrlOrNull()` and get info from that, instead of manual string handling.

2024-12-05 20:13 UTC, vetleledaal commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +            list.add(Page(i, "", imageUrl = imageUrl))
```suggestion
            list.add(Page(i, imageUrl = imageUrl))
```

2024-12-05 20:13 UTC, vetleledaal commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        return result
```suggestion
        return imageByteArray.mapIndexed { idx, byte ->
            byte xor hashByteArray[idx % hashByteArray.size]
        }.toByteArray()
```

2024-12-06 00:31 UTC, hatozuki-programmer commented
Thanks for the feedback, I've implemented the requested changes.

2024-12-06 06:57 UTC, bapeey reviewed
Some minor adjustments

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        }
```suggestion
        val details = json.decodeFromString<KadoComiWorkDto>(response.body.string())
```

Same for the others too

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        details.work.authors!!.forEach {
```suggestion
        details.work.authors?.forEach {
```

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        return list
```kt
        return details.latestEpisodes?.result.orEmpty().map { episode ->
            SChapter.create().apply {
               ....
            }
        }
```

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        return list
```kt
        val pages = viewer.manuscripts.mapIndexed { idx, manuscript ->
            Page(....))
        }

        if (pages.isEmpty()) {
            throw Exception(....)
        }

        return pages
```

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        return manga.url.split("/").reversed().first()
```suggestion
        return manga.url.split("/").last()
```

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        return list
```kt
    return results.result.map { 
        ....
    }
```

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComi.kt
> +        return list.joinToString()
```suggestion
        return listOfNotNull(work.genre?.name, work.subGenre?.name)
        .plus(work.tags?.map { it.name }.orEmpty())
        .joinToString()
```

2024-12-06 06:57 UTC, bapeey commented on src/ja/kadocomi/src/eu/kanade/tachiyomi/extension/ja/kadocomi/KadoComiDto.kt
> +data class KadoComiWorkDto(
```suggestion
class KadoComiWorkDto(
```

Remove the `data` annotation because it generates methods that aren’t being used

2024-12-06 23:26 UTC, hatozuki-programmer commented
Thanks for the additional feedback, I've implemented the requested changes.

2024-12-06 23:59 UTC, vetleledaal approved these changes

2024-12-07 21:01 UTC, merged