Hide paid chapters in MangaThemesiaAlt
keiyoushi/extensions-source pull request #6598
Opened 2024-12-13 18:01 UTC by lord-ne

Two of the sources using the `MangaThemesiaAlt` theme, NightScans and ThunderScans, have paid chapters which cannot be viewed in Mihon without purchasing (attempting to click them results in an error). This PR hides those chapters from the chapter list. It also adds a setting to go back to the old behavior of not hiding them (a user might want to use this, for example, to be notified when there are new paid chapters so that they can go and purchase them on the scanlator's website), but the default setting is to hide them.

Checklist:

- [x] N/A Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] N/A Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] N/A Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] N/A Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] N/A Have removed `web_hi_res_512.png` when adding a new extension

The new setting option:

![Screenshot from 2024-12-13 12-41-48](https://github.com/user-attachments/assets/dbbc1fca-e9f1-4ace-9e82-e5cdc8ad4729)

With hiding enabled:

![Screenshot from 2024-12-13 12-41-18](https://github.com/user-attachments/assets/7f7d083b-c8a7-45d6-b543-524527b95747)

With hiding disabled:

![Screenshot from 2024-12-13 12-42-13](https://github.com/user-attachments/assets/ce0c2a94-281b-4d9b-87a5-2aa39aadb759)

2024-12-14 10:44 UTC, AwkwardPeak7 commented
I don't think this needs to be in `MangaThemesiaAlt`, maybe in the base class, but imo just update selector in affected sources.
afaik lock system isn't part of the base wordpress theme, it comes with some addon, so different sources can have different selectors

2024-12-14 23:11 UTC, lord-ne commented
Two out of the three sources using the `MangaThemesiaAlt` base class (`NightScans` and `ThunderScans`) have this lock system, whereas none of the ones I checked using the regular `MangaThemesia` base class had it, so I assumed it was related to the theme. Do you know where it comes from?

2024-12-15 04:05 UTC, AwkwardPeak7 commented
Alt version have additional logic for dynamic urls (random part in manga url which changes every so often)

2024-12-18 15:06 UTC, lord-ne commented
I see a few ways forward here, so I'm writing them out here to get your thoughts:

1. Manually implement this for Night Scans and Thunder Scans.
  a. This is simple, but we'd be duplicating a lot of code. It would get pretty annoying if any more sources needed this, we'd be copying the code everywhere.
2. Create some helper methods in the `mangathemesia` lib to help implement this
  a. Basically all the sources would have to do is call the helper methods inside their `setupPreferenceScreen` and `chapterListSelector` functions. But I'm not sure if creating helper methods like that is really something we do in this codebase.
3. Keep the functionality in the `MangaThemesiaAlt` class
  a. This is pretty simple. We should probably have a boolean to enable/disable it even if we do keep it here; we don't want the preference showing up for sources that actually don't need it. 
4. Put the functionality in the `MangaThemesia` class
  a. This makes more sense conceptually than (3), but if it's tricky if we won't want the preference option to show up for sources that don't support it (which is most of them, so we probably do want to ensure it doesn't show up) because `MangaThemesia` doesn't currently have any preferences or inherit from `ConfigurableSource`, and we wouldn't want to have a blank preference screen show up.

I'm leaning towards (2), I'll throw together an implementation and see how it looks.

2024-12-18 16:29 UTC, lord-ne commented
Updates and bench tested. How does this implementation look @AwkwardPeak7 ?

2024-12-19 11:38 UTC, AwkwardPeak7 commented
honestly just change selector in those sources to block paid chapters without any preference to toggle it.... that is what we usually do for most of such sources and only add preference if users ask for it.

2024-12-19 13:41 UTC, lord-ne commented
I've actually been finding the toggle useful, some of these sites have decent coin rates where it's only like 10 cents per chapter, so on some of them I actually do want to leave the toggle off and buy the chapters.

2024-12-22 05:01 UTC, AwkwardPeak7 requested changes

2024-12-22 05:01 UTC, AwkwardPeak7 commented on src/all/thunderscans/src/eu/kanade/tachiyomi/extension/all/thunderscans/ThunderScansFactory.kt
make a ThunderScan class here with the changes then inherit both from this class

2024-12-23 06:15 UTC, AwkwardPeak7 approved these changes

2024-12-24 11:49 UTC, merged