[ru-Acomics] Fix parsing popular and search page
keiyoushi/extensions-source pull request #6611
Opened 2024-12-14 19:41 UTC by Pavkazzz

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

Closes #6120

2024-12-17 05:26 UTC, AwkwardPeak7 requested changes

2024-12-17 05:26 UTC, AwkwardPeak7 commented on src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt
> +    }
either throw `UnsupportedOperationException` on set to empty string

2024-12-17 05:26 UTC, AwkwardPeak7 commented on src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt
> +        return MangasPage(mangas, true)
is there not some end page? maybe check number of entries on page and end page would have less.

2024-12-18 22:59 UTC, vetleledaal commented on src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt
> +        TODO("Not yet implemented")
You are looking for `a.infinite-scroll` after the last `div.infinite-scroll-content > section.serial-card`. That element only exists if there is more content to load. You can make it as advanced or basic as you want.

2025-02-01 13:58 UTC, AwkwardPeak7 approved these changes

2025-02-01 13:58 UTC, merged