Baozi: add new domain
keiyoushi/extensions-source pull request #6658
Opened 2024-12-17 18:38 UTC by ifurther

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

2024-12-17 23:10 UTC, AnonymousPtBr commented
👍

2024-12-18 02:52 UTC, AwkwardPeak7 requested changes
you need to bump the version

2024-12-19 11:55 UTC, stevenyomi commented on src/zh/baozimanhua/src/eu/kanade/tachiyomi/extension/zh/baozimanhua/Baozi.kt
> +            "www.twmanga.com",
```suggestion
            "cn.twmanga.com",
            "tw.twmanga.com",
            "www.twmanga.com",
```

`czmanga.com` now redirects to the new domain.

2024-12-19 11:55 UTC, stevenyomi commented on src/zh/baozimanhua/AndroidManifest.xml
> +                <data android:host="czmanga.com" />
```suggestion
```

2024-12-19 12:27 UTC, ifurther commented on src/zh/baozimanhua/src/eu/kanade/tachiyomi/extension/zh/baozimanhua/Baozi.kt
> +            "www.twmanga.com",
Ok, I remove it

2024-12-20 12:04 UTC, stevenyomi approved these changes

2024-12-22 05:01 UTC, merged