Add MangaKuro
keiyoushi/extensions-source pull request #6717
Opened 2024-12-20 14:44 UTC by Creepler13

Closes: #6691

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [X] Have removed `web_hi_res_512.png` when adding a new extension

2024-12-20 20:40 UTC, vetleledaal requested changes

2024-12-20 20:40 UTC, vetleledaal commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +        val response = client.newCall(GET("https://mangakuro.net/ajax/image/list/chap/$id", headers)).execute()
Use `$baseUrl`

2024-12-20 20:40 UTC, vetleledaal commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +    private val imageRegex = """src=.?"(\S+)\\"""".toRegex()
Consider using `[^"]+` instead

2024-12-20 20:40 UTC, vetleledaal commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +        // date_upload = no real date in web
No suggested change, but out of curiosity, is there an app where this information is available?

2024-12-20 20:40 UTC, vetleledaal commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +            title = element.selectFirst(".mg_name a")?.text().toString()
`.toString()` is hiding the current behaviour of `?: ""`

2024-12-20 20:40 UTC, vetleledaal commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +            addPathSegment(page.toString())
In regards to caching on the site- when using the site is the first page explicitly set in the URL? We should aim to mimic this behavior to avoid unnecessarily caching pages on the remote.

2024-12-21 22:53 UTC, Creepler13 commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +        // date_upload = no real date in web
The only data available is the japanese verion of e.g: 5 months ago

2024-12-21 22:54 UTC, Creepler13 commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +            addPathSegment(page.toString())
Yes it is

2024-12-22 05:17 UTC, AwkwardPeak7 submitted a review, later dismissed

2024-12-22 05:17 UTC, AwkwardPeak7 commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +            title = element.selectFirst(".mg_name a")?.text() ?: ""
url and title are mandatory, use non null assertion

2024-12-22 05:17 UTC, AwkwardPeak7 commented on src/ja/mangakuro/src/eu/kanade/tachiyomi/extension/ja/mangakuro/MangaKuro.kt
> +        name = a?.text().toString().substringAfter("# ")
same here, use non null assertion

2024-12-22 15:00 UTC, vetleledaal approved these changes

2024-12-22 15:18 UTC, merged