WeebCentral add info to mangadetails
keiyoushi/extensions-source pull request #6840
Opened 2024-12-27 15:17 UTC by Creepler13

Closes #6684

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

2024-12-27 18:13 UTC, vetleledaal requested changes

2024-12-27 18:13 UTC, vetleledaal commented on src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt
> +            genre = selectFirst("ul > li:has(strong:contains(Type)) > a")!!.text()
genre is not critical, remove non-null assert.

2024-12-27 18:13 UTC, vetleledaal commented on src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt
> +            genre += ", " + select("ul > li:has(strong:contains(Tag)) > span > a").joinToString { it.text() }
You can just combine this selector with the previous one.

2024-12-27 18:13 UTC, vetleledaal commented on src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt
> +            description += selectFirst("li:has(strong:contains(Description)) > p")?.text()
Consider using `buildString {}` for `description`.

2024-12-27 18:13 UTC, vetleledaal commented on src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt
> +            if (selectFirst("""ul > li:has(a[href$="official=True"])""") != null) {
Use `~=` (contains) if there is no better selector. Usually you would use `'` for CSS to avoid string escaping issues.

2024-12-29 06:43 UTC, AwkwardPeak7 commented on src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt
> +            if (selectFirst("ul > li > strong:contains(Translation) + a:contains(Yes)") != null) {
maybe explicitly check "Official translation" instead of just translation?

2024-12-29 20:17 UTC, vetleledaal approved these changes

2024-12-30 15:41 UTC, merged